Harvey-OS/harvey

.travis.yml
this will send travis build status nottifications to slack.
=> travis build notifications to the slack channel

sys/src/9/riscv/core.json, sys/src/9/riscv/riscvcpu.json
Next step is to fill in with various .h files.
=> riscv: modifications for the current state.

riscv/include/ureg.h, sys/src/9/amd64/core.json, sys/src/9/port/port.json, sys/src/9/port/rebootcmd.c, sys/src/9/riscv/core.json, sys/src/9/riscv/dat.h, sys/src/9/riscv/fns.h, sys/src/9/riscv/mem.h, sys/src/9/riscv/riscvcpu.json
=> Move things around, but don't break rebooting with no file name.

sys/src/cmd/auth/factotum/fs.c, sys/src/cmd/auth/factotum/pass.c, sys/src/cmd/aux/flashfs/devfs.c, sys/src/cmd/aux/flashfs/entry.c, sys/src/cmd/aux/vga/vesa.c, sys/src/cmd/cdfs/main.c, sys/src/cmd/cifs/main.c, sys/src/cmd/clock.c, sys/src/cmd/ip/ppp/ppp.c, sys/src/cmd/ratrace.c, sys/src/regress/waserror.c
=> Removed most [-Wunused-variable] warnings

sys/src/9/riscv/core.json, sys/src/9/riscv/kernel.ld, sys/src/9/riscv/spike_util.c
=> riscv: it builds and may even run and print a message.

sys/include/libc.h, sys/src/9/port/lib.h
=> symlink support, step 1: constants.

bootstrap.sh
Change-Id: I6d649cd20dce132eee32441ae6409882104a0b98
Signed-off-by: Dan Cross <crossd@gmail.com>
=> Update generated text in bootstrap.sh.

bootstrap.sh, sys/src/libthread/exec.c
=> libthread: fix stdargs problem.

.pullapprove.yml
Make it so that I review Harvey changes again.
=> Add dancrossnyc as a harvey reviewer.

sys/include/pool.h, sys/src/9/amd64/qmalloc.c, sys/src/libc/port/malloc.c, sys/src/libmemdraw/alloc.c, sys/src/libmemdraw/draw.c
It looks like a bad interaction between the malloc pool and the image pool
when allocating images.  I've removed the image pool& it works.
Can someone check this out - it works, but I'm a bit twitchy I've missed
something. c.f. memimagemove
=> Fix for panic in Mahjongg #88

sys/src/cmd/build.json, sys/src/cmd/gdbserver/regsamd64.c
Make it a standard buld component too. Let's see if we can help alvaro!
=> Get gdb server building again

CONTRIBUTING.md, README.md
For formatting and grammar.
Change-Id: I2ff64fe16d735d431420db6e9c7e5a31de057ec2
Signed-off-by: Dan Cross <crossd@gmail.com>
=> Update README and CONTRIBUTING documents

sys/src/sysconf.json
=> Change chdir system call # to match linux

.travis.yml
It's not working correctly and the hack to fix it is breaking other things.
=> Take the new build out.

sys/src/sysconf.json
=> Another try at fixing system call #, recovering from mistaken add of 9sys.h

sys/include/mouse.h, sys/src/cmd/acme/acme.c, sys/src/cmd/acme/scrl.c, sys/src/cmd/rio/dat.h, sys/src/cmd/rio/rio.c, sys/src/cmd/rio/scrl.c, sys/src/cmd/rio/wind.c, sys/src/cmd/samterm/io.c, sys/src/libdraw/klibdraw.json, sys/src/libdraw/libdraw.json, sys/src/libdraw/mouse.c, sys/src/libframe/libframe.json
I don't know the right way to do the mouse bits, see what you think.
But it works, or seems to.
=> More deanon.

sys/src/libc/9sys/syslog.c, sys/src/libc/klibc.json, sys/src/libc/libc.json, sys/src/libc/port/pool.c
Author:    Keith Poole <keith.poole@gmail.com>
=> libc now compiles

sys/include/9p.h, sys/src/cmd/archfs.c, sys/src/cmd/aux/olefs.c, sys/src/lib9p/file.c, sys/src/lib9p/intmap.c, sys/src/lib9p/lib9p.json, sys/src/lib9p/srv.c, sys/src/lib9p/uid.c
Signed-off-by: Keith Poole <keith.poole@gmail.com>
=> lib9p builds

sys/src/cmd/aux/aux.json, sys/src/cmd/rio/dat.h, sys/src/cmd/rio/fsys.c, sys/src/cmd/rio/rio.c, sys/src/cmd/rio/rio.json, sys/src/cmd/rio/scrl.c, sys/src/cmd/rio/wctl.c, sys/src/cmd/rio/wind.c, sys/src/cmd/rio/xfid.c
=> clang changes for rio.

sys/src/cmd/acme/acme.c, sys/src/cmd/acme/addr.c, sys/src/cmd/acme/build.json, sys/src/cmd/acme/cols.c, sys/src/cmd/acme/dat.h, sys/src/cmd/acme/ecmd.c, sys/src/cmd/acme/elog.c, sys/src/cmd/acme/exec.c, sys/src/cmd/acme/file.c, sys/src/cmd/acme/fsys.c, sys/src/cmd/acme/look.c, sys/src/cmd/acme/regx.c, sys/src/cmd/acme/rows.c, sys/src/cmd/acme/scrl.c, sys/src/cmd/acme/text.c, sys/src/cmd/acme/util.c, sys/src/cmd/acme/wind.c, sys/src/cmd/acme/xfid.c, sys/src/cmd/archfs.c, sys/src/cmd/aux/accupoint.c, sys/src/cmd/aux/aux.json, sys/src/cmd/aux/gps/gps.json, sys/src/cmd/aux/gps/gpsfs.c, sys/src/cmd/build.json, sys/src/cmd/clock.c, sys/src/cmd/cpu.c, sys/src/cmd/ecp.c, sys/src/cmd/file.c, sys/src/cmd/sed.c, sys/src/cmd/trace.c
I also removed acme as a default application
=> cmd & subdirectories no longer need plan9 extensions

sys/include/scribble.h, sys/src/libcontrol/box.c, sys/src/libcontrol/button.c, sys/src/libcontrol/control.c, sys/src/libcontrol/entry.c, sys/src/libcontrol/group.c, sys/src/libcontrol/group.h, sys/src/libcontrol/keyboard.c, sys/src/libcontrol/label.c, sys/src/libcontrol/libcontrol.json, sys/src/libcontrol/menu.c, sys/src/libcontrol/radiobutton.c, sys/src/libcontrol/scribble.c, sys/src/libcontrol/slider.c, sys/src/libcontrol/tabs.c, sys/src/libcontrol/text.c, sys/src/libcontrol/textbutton.c, sys/src/libcontrol/textbutton3.c
Not really building without plan9-extensions but this is a step.
=> deanon libcontrol

sys/include/usb/ether.h, sys/include/usb/serial.h, sys/include/usb/ums.h, sys/include/usb/usb.h, sys/src/libusb/audio/audiofs.c, sys/src/libusb/build.json, sys/src/libusb/disk/disk.c, sys/src/libusb/ether/asix.c, sys/src/libusb/ether/ether.c, sys/src/libusb/ether/smsc.c, sys/src/libusb/kb/kb.c, sys/src/libusb/lib/dev.c, sys/src/libusb/lib/dump.c, sys/src/libusb/lib/fsdir.c, sys/src/libusb/serial/ftdi.c, sys/src/libusb/serial/prolific.c, sys/src/libusb/serial/serial.c, sys/src/libusb/serial/silabs.c
Signed-off-by: Keith Poole <keith.poole@gmail.com>
=> Removed plan9 extensions from libusb

sys/src/cmd/build.json
Including acid in cmd/build.json
=> Including acid in general build

.travis.yml
=> clang: add clang to the testing

sys/src/cmd/aux/consolefs.c, sys/src/cmd/aux/depend.c, sys/src/cmd/aux/disksim.c, sys/src/cmd/aux/searchfs.c, sys/src/cmd/bzip2/lib/compress.c, sys/src/cmd/disk/mkext.c, sys/src/cmd/disk/prep/fdisk.c, sys/src/cmd/dossrv/dat.h, sys/src/cmd/dossrv/dosfs.c, sys/src/cmd/dossrv/dossubs.c, sys/src/cmd/dossrv/fns.h, sys/src/cmd/dossrv/iotrack.c, sys/src/cmd/ip/gping.c, sys/src/cmd/ip/httpd/content.c, sys/src/cmd/ip/ip.json, sys/src/cmd/ratrace.c, sys/src/cmd/stats.c, sys/src/cmd/usb/usbd/usbd.c
Lots left to do, but you can only stand to do this a little at a time :)
=> clang: more cleanup

bootstrap.sh, rc/bin/cpurc, rc/bin/print1, usr/harvey/lib/profile
bootstrap.sh changed to include instructions to make drawterm
work correctly.
=> Removed dependency on awk in cpurc

rc/bin/setrtc
setrc script is called from fshalt.
=> Replacing awk for field

sys/src/cmd/build.json
It gets lots of warnings though.
=> add acme back.

bootstrap.sh, util/VMPXE, util/continuous-build.sh, util/gdb-kstack.sh, util/run-minicluster.sh
I did a cursory glance of the scripts, I didn't see any bashisms. Improves build on OpenBSD.
=> Use /bin/sh instead of bash for more portability

sys/src/cmd/build.json
=> add iozone fileop to standard build.

sys/src/9/amd64/devacpi.c, sys/src/9/amd64/main.c, sys/src/9/amd64/trap.c
This all boots now. The big problem remaining is the
antiquated Plan 9 APIC bits. The work is only beginning.
But we seem to have ACPICA. I can even see messages
from what looks like the AML parser.
=> ACPI: add pci config supoprt and other functions.

.mailmap, CONTRIBUTORS
`git log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf > CONTRIBUTORS`
=> mailmap to create the contributors list

sys/src/9/amd64/build.json
=> Removed sdata to fix cd hang problem

sys/src/9/amd64/apic.c, sys/src/9/amd64/core.json, sys/src/9/amd64/devacpi.c, sys/src/9/amd64/fns.h, sys/src/9/amd64/ioapic.c, sys/src/9/amd64/main.c, sys/src/9/amd64/mp.c, sys/src/9/port/devcons.c, sys/src/9/port/hexdump.c, sys/src/9/port/proc.c, sys/src/libacpi/acpica/kacpiflags.json
I'm not saying this is right, only that it appears to do no harm.
=> ACPI work.

sys/src/regress/fs/build.json, sys/src/regress/fs/chdir.c, sys/src/regress/fs/filewrite.c, sys/src/regress/fs/fs.rc
run regress/fs.rc '#@' to run tests
=> Ramdisk test

util/clang-format-diff.py
add clang diff formatter
```
git diff -U0 HEAD^ | clang-format-diff.py -p1 -i
```
=> util: clang diff formatter

.travis.yml, amd64/include/cflags.json, amd64/include/klib.json, sys/src/9/amd64/core.json
=> ci: add gcc-6 to the matrix

CONTRIBUTING.md, README.md
contributing is fine but the what is harvey section in read me needs help.
=> gh: update contributing and readme files

sys/src/9/amd64/archamd64.c
I guess, like my X4, this AMD series must be treated as a K8
Opteron, leaving Phenom (hybrid) as a rare case of K10.
=> Fixing detection of Athlon II X2 B24

sys/src/cmd/ms.c
=> Send mouse pointer offsets encoded in decimal. This fixes issue 272.

util/GO9PRUN
Always enable ACPI on KVM. We need to keep this testing.
=> ACPI: working on some things.

sys/include/libc.h, sys/src/9/port/sysproc.c, sys/src/libc/libc.json, sys/src/sysconf.json
Should work for you too I hope. Please tests.
=> sysr0: bring back sysr0

usr/harvey/readme.acme
=> glenda -> harvey

rc/bin/B, sys/src/cmd/build.json, sys/src/cmd/plumb/plumb.json, usr/harvey/lib/profile
"plumber" wasn't built by default, "plumb" now gets a build file,
added plumber to the harvey profile invocation, and restored the
overzealously-removed /rc/bin/B
=> Restore some plumbing capabilities.

mnt/plumb/.gitignore
Change-Id: I9c6d9dac3e5def4471291361f1179c0f220093cf
=> Adding /mnt/plumb for making happy drawterm

sys/src/cmd/samterm/io.c
In io.c, put `Mouse *` in Alt.v instead of `Mouse **`
Change-Id: I3eb18146b2b770fc466259b8cdc76f9983049791
Signed-off-by: Hank Donnay <hdonnay@gmail.com>
Also hit the file with `clang-format`. Actual changes occur on lines 134 & 151.
=> sys/src/cmd/samterm: fix suicide on mouse movement

sys/include/virtio_blk.h, sys/include/virtio_config.h, sys/include/virtio_console.h, sys/include/virtio_ids.h, sys/include/virtio_net.h, sys/include/virtio_pci.h
=> virtio: bring in include files from Linux 2c9b3ebd5913c2d1371b749a8057ac32972b410d (OK to merge as proposed)

sys/src/regress/bindtest.c, sys/src/regress/build.json
=> Add a bind regression test (it fails)

README.md
I show this detail in other repos and I liked it.
=> License image.

aarch64/include/mach_acpi.h, sys/src/cmd/aux/console/utils.c, sys/src/cmd/zenith/util.c
=> More stack backtraces saved.

sys/src/9/port/devether.c
Clean up the logic to make it easier to follow.
=> Clean up devether.c

sys/src/9/port/devvcon.c, sys/src/9/port/virtio_lib.c
=> Fix virtio-lib panic when no virtual devices enabled.

sys/src/9/boot/BUILD, sys/src/ARCHS
=> sys/src: move arches to sys src so it can be shared

bootstrap.sh, util/continuous-build.sh
I've tried this a few times and it works fine.
=> Fix bootstrap.h so bldy works

BUILD, sys/src/9/amd64/BUILD
=> bldy: change the name of the objcopy file

.gitignore, amd64/include/cflags.json, sys/src/9/amd64/core.json
Signed-off-by: Keith Poole <keith.poole@gmail.com>
=> Changed compile flags to allow gdb to work correctly

.gitignore, sys/src/9/port/devmnt.c
Fix for issue #110
Signed-off-by: Keith Poole <keith.poole@gmail.com>
=> Changed qremove to qget in devmnt.c

sys/src/9/riscv/trap.c, sys/src/9/riscv/uart.c, sys/src/9/riscv/uart8250mem.c
They don't quite work. rc does not start up for some reason.
=> riscv: lowriscv: some non working hacks for the lowrisc platform

bootstrap.sh
=> bootstrap: fix the bldy start instructions

sys/src/cmd/screenlock.c
Handle case where image isn't found, and tidy code a bit.
=> Fix warning in screenlock, handle image not found better

amd64/gcc-4.8.BUILD, amd64/gcc-5.BUILD, amd64/gcc-6.BUILD
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841420
=> GCC flags for bldy in Debian

CONTRIBUTORS
Requested by a contributor
Change-Id: I7c92d2e62007c37cf2726933ee787b9b59d981cf
=> Editing CONTRIBUTORS file

CONTRIBUTORS
Change-Id: I3eb7a5c5e663b2433a229aa3703a4e5b1b56193b
=> Requested by user

sys/src/9/port/devregress.c
Signed-off-by: rminnich <rminnich@gmail.com>
=> devregress: change dc to ξ

sys/src/9/amd64/BUILD, sys/src/9/amd64/build.json
Now I have an ES keyboard map :-)
=> Keymaps are back

util/src/harvey/cmd/build/build.go
we're multicompiler, after all.
=> build: require that CC be set

amd64/include/gcc-4.8.json, amd64/include/gcc-5.json, amd64/include/gcc-6.json, amd64/include/gcc.json, amd64/include/klib.json, sys/src/9/amd64/core.json, util/src/harvey/cmd/build/build.go
All our configs are now in one place.
-fno-pie is the order of the day.
=> build: remove last vestiges of toolopt

sys/src/9/amd64/devacpi.c, sys/src/9/amd64/fns.h, sys/src/9/amd64/main.c, sys/src/cmd/acpi/TestACPISleep.c, sys/src/cmd/acpi/build.json
nothing is handled yet, that's next; we need to queue things
to a process.
=> ACPI: enable interrupts

sys/src/9/amd64/devacpi.c, sys/src/9/amd64/devarch.c
They don't seem to have caused problems after all but someone
should test with terminals.
=> ACPI: re enable reservation of IO ports

sys/src/9/amd64/devacpi.c
=> acpi: only enable acpi interrupts if someone is reading the acpiintr file

README.md
=> README.md: add the SFC donate button

sys/src/9/port/devtab.c
=> devtabreset: check to make sure all .dc are unique

sys/src/cmd/acpi/build.json, sys/src/libacpi/harvey.c
=> acpi: bring harvey.c changes in and re-enable building TestACPISleep.c

sys/src/9/amd64/mmu.c, sys/src/9/boot/boot.c, sys/src/9/boot/bootip.c, sys/src/cmd/usb/usbd/usbd.c
Add newlines where they seem to have been missed.
=> Tidy kernel messages

sys/include/draw.h, sys/src/cmd/stats.c, sys/src/libdraw/openfont.c
=> New opendefaultfont in libdraw

sys/src/cmd/acme/text.c
Fixed a problem that provokes a crash in acme when you reach at the end of a document and press the key down.
=> Fix acme suicide.

usr/harvey/lib/profile
=> make $font the default font for acme

sys/src/cmd/winwatch.c
=> Winwatch meets default font

lib/namespace
=> Useless namespace

sys/src/cmd/acid/builtin.c
=> The syscall is sysr0

usr/harvey/bin/rc/riostart, usr/harvey/lib/acme.dump, usr/harvey/lib/acme.dump.small, usr/harvey/lib/plumbing
=> Changed some scripts to use /usr/harvey instead of /usr/glenda

sys/src/9/386/i8042.c, sys/src/9/port/devkbmap.c, sys/src/9/port/portfns.h
This allow us to support dead keys in keyboards. Now we can have full functionality of latin keyboards (spanish, french, portuguese, ...).
Next I'll define a complete spanish keyboard and write some tutorial how to write a kbmap to harvey.
This changes don't affect standar US keyboard behaviour and the other kbmaps that we have now in /sys/lib/kbmap.
=> Keyboard dead keys support

sys/src/9/amd64/main.c, sys/src/9/amd64/trap.c, sys/src/9/port/portdat.h, sys/src/9/test/1/main.c
Signed-off-by: Rafael Fernandez <rafita.fernandez@gmail.com>
=> Removed conffile from kernel

sys/src/cmd/gdbserver/gdbstub.c
=> Remove debug logging

sys/src/cmd/gdbserver/gdbstub.c
=> Avoiding gcc warnings of 'if' indentation.

util/GO9PTERM
=> Forward port used by gdb (1666) in GO9PTERM

sys/src/cmd/gdbserver/debug_core.h, sys/src/cmd/gdbserver/gdbstub.c
If we eventually want to support multiple processes, can re-add.
=> Only send the main pid to gdbserver on qfThreadInfo

Dockerfile, util/GO9PCPUDOCKER
by bringing the Dockerfile to the main repo we make sure that
a docker image is built everytime something is commited to
the master branch. A hypothetical user can come in and start
running harvey by
docker run harveyos/harvey
R=fuchicar
=> docker: bring docker integration in to the main repo

sys/src/libhttpd/date.c, sys/src/libhttpd/gethead.c, sys/src/libhttpd/hio.c, sys/src/libhttpd/httpunesc.c, sys/src/libhttpd/lower.c, sys/src/libhttpd/parse.c, sys/src/libhttpd/parsereq.c, sys/src/libhttpd/redirected.c, sys/src/libhttpd/urlunesc.c
Add a few build artifacts to .gitignore.
=> .gitignore: Ignore binaries and stuff.

amd64/include/cflags.json, amd64/include/gcc-4.8.json, amd64/include/gcc-5.json, amd64/include/gcc.json, amd64/include/klib.json, sys/src/9/aarch64/inith.json
Warn on ALL the things!
Well, maybe not all, but more than before.
=> Expose more warnings.

sys/src/cmd/auth/as.c, sys/src/cmd/auth/cron.c, sys/src/cmd/auth/keyfs.c, sys/src/cmd/auth/uniq.c, sys/src/cmd/auth/warning.c
They just keep coming and coming and coming....
=> Fix more warnings.

sys/src/cmd/aux/realemu/fmt.c
Need some parenthesis around some boolean expressions.
=> Fix another precedence bug in realemu

sys/src/cmd/gdbserver/debug_core.h, sys/src/cmd/gdbserver/gdb.h, sys/src/cmd/gdbserver/gdbstub.c, sys/src/cmd/gdbserver/regsaarch64.c, sys/src/cmd/gdbserver/regsamd64.c, sys/src/cmd/gdbserver/regsriscv.c
- Implement single step (still needs some work)
- Removes some unused code
- Better matches the spec for qSymbol::
- Tries to fix bug when a single register value is requested
=> First pass at single-step

sys/src/9/port/devproc.c, sys/src/cmd/gdbserver/gdbstub.c
=> Reduce noise in gdb logs and debug output

amd64/include/clang-3.4.json, amd64/include/clang-3.5.json, amd64/include/clang-3.6.json, amd64/include/clang-3.7.json, amd64/include/clang-3.8.json, amd64/include/clang.json, amd64/include/gcc-4.8.json, amd64/include/gcc-5.json, amd64/include/gcc-6.json, amd64/include/gcc.json
=> Reformat some JSON and remove an option for clang.

sys/src/cmd/9660srv/9660srv.c, sys/src/cmd/9660srv/main.c, sys/src/cmd/9660srv/xfile.c, sys/src/cmd/acme/ecmd.c, sys/src/cmd/acme/regx.c, sys/src/cmd/acme/util.c, sys/src/cmd/dict/ahd.c, sys/src/cmd/dict/pcollinsg.c, sys/src/cmd/dict/robert.c, sys/src/cmd/dossrv/iotrack.c, sys/src/cmd/dossrv/xfile.c, sys/src/cmd/ext2srv/xfile.c, sys/src/cmd/sam/address.c, sys/src/cmd/sam/regexp.c, sys/src/cmd/sam/shell.c, sys/src/cmd/sam/string.c, sys/src/cmd/sum.c, sys/src/cmd/vnc/devdraw.c, sys/src/cmd/zenith/ecmd.c, sys/src/cmd/zenith/regx.c, sys/src/cmd/zenith/util.c, sys/src/libc/port/atnotify.c, sys/src/libc/port/pool.c, sys/src/libregexp/regexec.c, sys/src/libstdio/dtoa.c
Remove a bunch of no-longer-relevant comments about
assignments in loops and conditionals.
=> More broken windows: now-redundant 'assign' comments.

sys/src/cmd/gdbserver/gdbstub.c
detach will start the process after removing all breakpoints.
kill will properly kill the process.
=> Improve gdb's handling of detach and kill

sys/src/cmd/gdbserver/gdbstub.c
=> Code formatting and removing unused code

sys/src/cmd/gdbserver/gdbstub.c
Previously, gdb expected process to already be stopped.  Now we do it immediately.
Also, it seems syminit was never finding any symbols, and wasn't doing anything useful anyway.  It's maybe a little broken.
=> Stop process when connecting gdb

sys/src/cmd/field.c
=> Fix bugs in field.c

sys/src/libs.json, sys/src/libufs/build.json, sys/src/libufs/ffs/ffs_tables.c, sys/src/libufs/ffs/fs.h
As you get files to build, from them from
to
SourceFiles
=> libufs: build file

sys/src/libufs/ffs/ffs_alloc.c, sys/src/libufs/port-scripts/scalar.cocci, sys/src/libufs/ufs/ufs_dirhash.c
This change was created via:
spatch --in-place --dir . --sp-file port-scripts/scalar.cocci
This is a model you can use for more spatch work.
=> ufs: create example script and apply it

sys/include/hashmap.h, sys/src/libc/libc.json, sys/src/libc/port/hashmap.c, sys/src/regress/hashmap.c
this includes a test. It needs a fix in the formatting: what is %z%u in the
plan 9 world?
=> hash: add hash function from aki

sys/src/cmd/mug.c
=> mug: initiliaze Point p

sys/src/libufs/ffs/ffs_extern.h, sys/src/libufs/ufs/dir.h, sys/src/libufs/ufs/dirhash.h, sys/src/libufs/ufs/extattr.h, sys/src/libufs/ufs/inode.h, sys/src/libufs/ufs/quota.h, sys/src/libufs/ufs/ufsmount.h
Added the option --macro with the port-scripts/macros.h to get better results from spatch.
=> Run scalar.cocci over all files

amd64/include/gcc-7.json, sys/src/cmd/mug.c
Tested: gcc-7 (Ubuntu 7-20170407-0ubuntu2)
7.0.1 20170407 (experimental)
[trunk revision 246759]
=> Adding support for GCC 7

sys/src/libufs/ffs/ffs_alloc.c, sys/src/libufs/ffs/ffs_snapshot.c, sys/src/libufs/ffs/ffs_suspend.c, sys/src/libufs/ffs/ffs_vfsops.c, sys/src/libufs/ffs/softdep.h, sys/src/libufs/port-scripts/scalar.cocci, sys/src/libufs/ufs/quota.h, sys/src/libufs/ufs/ufs_gjournal.c, sys/src/libufs/ufs/ufs_lookup.c, sys/src/libufs/ufs/ufs_quota.c, sys/src/libufs/ufs/ufs_vnops.c, sys/src/libufs/ufs/ufsmount.h
=> (libufs) Convert u_long to uint64_t

sys/src/9/amd64/build.json, sys/src/9/port/devufs.c, sys/src/9/port/port.json
Framework for UFS2 kernel device
=> devufs skeleton

sys/src/9/port/devufs.c, sys/src/9/port/lib.h
Also noticed that the strlen declaration was missing const modifier.  Others are missing, but can be added separately.
=> Add dummy mount file and directory to devufs

sys/include/libufs.h, sys/src/9/amd64/core.json, sys/src/9/port/devufs.c, sys/src/klibs.json, sys/src/libs.json, sys/src/libufs/ffs/ffs_vfsops.c, sys/src/libufs/klibufs.json, sys/src/libufs/libufs.json
Followed the pattern of other kernel+user libraries.
=> Build kernel and user version of libufs, strip down and build ffs_vfsops.c

sys/src/cmd/newfs/mkfs.c, sys/src/cmd/newfs/newfs.c, sys/src/cmd/newfs/newfs.h
=> Add newfs from FreeBSD for creating UFS filesystems

sys/include/libufs.h, sys/src/9/port/devufs.c, sys/src/libufs/klibufs.json, sys/src/libufs/libufs.json, sys/src/libufs/ufs_harvey.c, sys/src/libufs/ufs_harvey.h
Can only mount one file currently, and can't unmount it yet.
Takes into account some of Ron's comments about the previous aborted commit.  Still need to add Refs - should hopefully be in next PR.
=> Mount UFS file with devufs

sys/src/cmd/newfs/mkfs.c, sys/src/cmd/newfs/newfs.c
Fix references to NULL in newfs code
Signed-off-by: Dave MacFarlane <driusan@gmail.com>
=> Replace NULL with nil in newfs

sys/src/9/ufs/ffs/ffs_extern.h, sys/src/9/ufs/ffs/ffs_snapshot.c, sys/src/9/ufs/ffs/ffs_softdep.c, sys/src/9/ufs/ffs/ffs_subr.c, sys/src/9/ufs/ffs/ffs_vfsops.c, sys/src/9/ufs/ffs/fs.h, sys/src/9/ufs/ffs/softdep.h, sys/src/9/ufs/ufs/ufs_vfsops.c, sys/src/9/ufs/ufs/ufsmount.h
- Rename fs -> Fs
- Make bread behave more like FreeBSD's version
I found myself making these changes in amongst a bunch of other changes, so decided to pull these out into their own isolated PR.
=> A bit of UFS refactoring

sys/src/9/ufs/ffs/ffs_vfsops.c, sys/src/9/ufs/ufs/inode.h, sys/src/9/ufs/ufs/ufs_vnops.c, sys/src/9/ufs/ufs_harvey.c, sys/src/9/ufs/ufs_harvey.h, sys/src/9/ufs/ufs_mountpoint.c
+ rename some of the vnode fields
=> UFS - Use RWlock for the vnlock

sys/src/9/port/devufs.c, sys/src/9/ufs/ufs/dir.h, sys/src/9/ufs/ufs/ufs_inode.c, sys/src/9/ufs/ufs/ufs_lookup.c, sys/src/9/ufs/ufs_ext.h, sys/src/9/ufs/ufs_harvey.c, sys/src/9/ufs/ufs_harvey.h
A previous attempt at enabling the lookup code showed that it's going to be a lot of work, so I'm going to try to do it in smaller chunks.
This change is mainly prep to get started.  Also removed some vnode types I don't think we'll use.
=> Start work for UFS inode lookup

sys/src/9/amd64/core.json
Arch, I'm disappointed in you, we should not have to do this.
=> Set -fno-stack-protector

sys/src/9/ufs/ffs/ffs_vfsops.c, sys/src/9/ufs/ufs/ufs_vfsops.c, sys/src/9/ufs/ufs/ufs_vnops.c, sys/src/9/ufs/ufs_harvey.c, sys/src/9/ufs/ufs_harvey.h
Breaking up previous PR into smaller, more isolated ones.
=> Add locking 'asserts' and improve locking of new vnodes

sys/include/ufs/ufsmount.h, sys/src/9/ufs/ffs/ffs_extern.h, sys/src/9/ufs/ffs/ffs_subr.c, sys/src/9/ufs/ffs/ffs_vfsops.c, sys/src/9/ufs/ufs_harvey.c, sys/src/9/ufs/ufs_harvey.h
Also move bread to somewhere more central.
=> Implement ffs_blkatoff

sys/src/9/port/devufs.c, sys/src/9/ufs/ffs/ffs_extern.h, sys/src/9/ufs/ffs/ffs_softdep.c, sys/src/9/ufs/ffs/ffs_suspend.c, sys/src/9/ufs/ffs/ffs_vfsops.c, sys/src/9/ufs/ufs.json, sys/src/9/ufs/ufs/ufs_extern.h, sys/src/9/ufs/ufs/ufs_vfsops.c, sys/src/9/ufs/ufs_ext.h
Apologies, needs to be approved again.
=> Hook up UFS init/uninit functions (though they don't do anything)

sys/include/ufs/libufs.h, sys/src/libufs/block.c, sys/src/libufs/build.json, sys/src/libufs/cgroup.c, sys/src/libufs/inode.c, sys/src/libufs/sblock.c, sys/src/libufs/type.c
Unchanged from FreeBSD code, same version as it was when we got the rest of the UFS code.
Added a build.json.
=> 	Add libufs from FreeBSD

sys/src/libufs/block.c, sys/src/libufs/cgroup.c, sys/src/libufs/sblock.c, sys/src/libufs/type.c
=> Fix up some included in libufs

sys/src/9/amd64/archamd64.c
=> Adding 4th Intel Ivy generation and AMD Ryzen

sys/src/cmd/newfs/mkfs.c, sys/src/cmd/newfs/newfs.c
Add some extensively used macros, change printfs to prints and fprints, change exit to exits.
Get the noise out of the way to make more interesting changes clearer.
=> Easy newfs changes

sys/include/ufs/libufs.h, sys/src/cmd/build.json, sys/src/cmd/newfs/build.json, sys/src/cmd/newfs/mkfs.c, sys/src/cmd/newfs/newfs.c, sys/src/cmd/newfs/newfs.h, sys/src/libufs/type.c
Get newfs building and running.  Handles the basic arguments.  Some other arguments removed.  Also handles creating or opening a file.
The goal is to get the command handling all the relevant args properly before moving into the guts of mkfs.c.
=> Add newfs to build, start adding arguments

sys/src/cmd/newfs/newfs.c, sys/src/cmd/newfs/newfs.h
=> newfs - handle all valid args

sys/include/ffs/fs.h, sys/include/ufs/dinode.h, sys/include/ufs/dir.h, sys/include/ufs/freebsd_util.h, sys/include/ufs/libufs.h, sys/include/ufs/ufsdat.h, sys/src/cmd/newfs/mkfs.c, sys/src/cmd/newfs/newfs.c, sys/src/cmd/newfs/newfs.h, sys/src/libufs/block.c
Can now create a ufs file image.
A few things still to do:
- Set the group once we decide what to do about group and user ids in the file system
- Remove the dinode union - we only need the UFS2 dinode
- Figure out why 0.00MB is output by newfs
(I thought I'd pushed the first commit already...  anyway)
=> Enable remaining newfs code

sys/src/cmd/newfs/mkfs.c
=> Remove traces of ufs1 from newfs code

sys/include/ffs/fs.h, sys/include/ufs/ufsmount.h, sys/src/9/ufs/ffs/ffs_extern.h, sys/src/9/ufs/ffs/ffs_softdep.c, sys/src/9/ufs/ffs/ffs_vfsops.c, sys/src/9/ufs/ufs_harvey.c, sys/src/9/ufs/ufs_mountpoint.h, sys/src/cmd/newfs/mkfs.c
Also remove some duplicate code.  Found while examining the superblock.
=> Remove some more UFS1 code

sys/src/9/port/devufs.c, sys/src/9/ufs/ufs_ext.h, sys/src/9/ufs/ufs_mountpoint.c
E.g. cat /dev/ufs/0/superblock
=> Add file to devufs to dump out the superblock

sys/src/9/port/lib.h, sys/src/9/ufs/ffs_vfsops.c, sys/src/9/ufs/ufs_harvey.c, sys/src/9/ufs/ufs_harvey.h, sys/src/9/ufs/ufs_mountpoint.c, sys/src/9/ufs/ufs_mountpoint.h, sys/src/cmd/newfs/mkfs.c
Also, I shouldn't have added lrand() to the kerel lib.h.  This function uses a different Lock to that in the kernel (but with same name), and ths caused problems.
=> Display inode details

sys/src/9/port/devufs.c, sys/src/9/ufs/ufs_ext.h, sys/src/9/ufs/ufs_mountpoint.c
=> Add support to devufs for dumping out contents of inode's file

sys/src/9/port/devufs.c, sys/src/9/ufs/ufs_ext.h, sys/src/9/ufs/ufs_harvey.c, sys/src/9/ufs/ufs_mountpoint.c
Beginnings of code to read inode file data
=> UFS Keep vnode from open to close

sys/include/ufs/inode.h, sys/include/ufs/ufsmount.h, sys/src/9/port/devufs.c, sys/src/9/ufs/ffs_vfsops.c, sys/src/9/ufs/ufs.json, sys/src/9/ufs/ufs_harvey_external.c, sys/src/9/ufs/ufs_harvey_internal.c, sys/src/9/ufs/ufs_harvey_vnode.c, sys/src/9/ufs/ufsfns.h
Trying to consolidate harvey-specific code into sensible .c and .h files.
Reading is in progress, this is more prep work.
=> Another UFS tidying up commit

sys/src/9/port/devufs.c, sys/src/9/ufs/ufs_harvey_external.c
=> Better error checking in devufs, release chan when releasing mp

sys/src/cmd/cfs/build.json, sys/src/cmd/ext2srv/build.json, sys/src/cmd/htmlroff/build.json, sys/src/cmd/map/build.json, sys/src/cmd/scat/build.json, sys/src/cmd/tbl/build.json, sys/src/cmd/troff2html/build.json
=> Fixing json files

README.md
=> Fixing logo in README since main website was changed

LICENSE.mit, README.md, sys/include/libsec.h, sys/include/mp.h, sys/src/libsec/port/tlshand.c, sys/src/libsec/port/x509.c
=> Adding MIT License for 9front code in libsec remaining mixed files

README.md
=> Fixing link in readme to right MIT license

RUN_ME_FIRST, bootstrap.sh, util/src/harvey/cmd/build/build.go, util/src/harvey/cmd/build/codegen.go, util/src/harvey/cmd/build/doc.go, util/src/harvey/cmd/build/paths.go, util/src/harvey/cmd/build/paths_harvey.go
Bringing back bootstrap script and a Build version with last functionalities, also remove the old RUN_ME_FIRST script
=> Bringing back bootstrap.sh  and a Build

sys/src/libavl/avl.c
=> Reintroducing libavl, dead code removed

sys/src/libframe/frdraw.c
=> Reintroducing libframe, removing dead variable

sys/src/libgeometry/matrix.c, sys/src/libgeometry/tstack.c
=> Reintroducing libgeometry, obsolete register type

sys/src/libmemdraw/draw.c
=> Reintroducing libmemdraw, some indentation fixes

sys/src/libventi/packet.c
=> Reintroducing libventi, removing getcallerpc arg

sys/src/libstdio/dtoa.c, sys/src/libstdio/vfprintf.c, sys/src/libstdio/vfscanf.c
=> Reintroducing libstdio, adding standard varargs

sys/src/cmd/file.c, sys/src/cmd/hget.c, sys/src/cmd/html2ms.c, sys/src/cmd/import.c, sys/src/cmd/kprof.c, sys/src/cmd/prof.c, sys/src/cmd/ps.c, sys/src/cmd/rdbfs.c, sys/src/cmd/tprof.c
=> Fix some clang errors in the cmds

sys/include/libc.h, sys/src/9/port/lib.h, sys/src/libc/9sys/abort.c, sys/src/libc/amd64/argv0.c, sys/src/libc/klibc.json, sys/src/libc/libc.json
=> Removing useless macro in libc

sys/src/libthread/libthread.json
=> Make libthread build file architecture independent

sys/src/cmd/exportfs/exportfs.c, sys/src/cmd/exportfs/exportfs.h, sys/src/cmd/ip/ftpd.c
=> Fix more cmd errors - exportfs, ftpd

sys/src/libc/9sys/read.c, sys/src/libc/9sys/write.c
=> Fixing read/write a la NIX

sys/src/9/port/sysfile.c
=> Adjusting syscalls to new offset for read/write

sys/src/9/port/devmnt.c
=> Re-add missing comparison from last last commit.

386/bin/replica/changes, 386/bin/replica/pull, 386/bin/replica/push, 386/bin/replica/scan, 386/bin/replica/setupdirs
=> Delete since these scripts are wrappers for scripts in rc/bin/replica

clean.json, sys/src/9/amd64/clean.json, sys/src/cleanlibs.json, sys/src/cmd/clean.json
Make clean more thorough - found more files by running git clean -nx
=> Clean more files

.travis.yml, util/ci.sh
=> ci: bring back travis file

rc/bin/tests/ramdisk, sys/src/9/port/devramfs.c
Signed-off-by: keith.poole <keith.poole@gmail.com>
=> Another attempt to get this change into master

sys/src/cmd/ratrace.c
Signed-off-by: keith.poole <keith.poole@gmail.com>
=> ratrace now displays usage if no arguments are given

sys/src/9/amd64/acore.c, sys/src/9/amd64/fpu.c, sys/src/9/riscv/acore.c
Make things a little easier to understand.
=> FPU - make some functions static

sys/include/draw.h, sys/include/mouse.h, sys/src/libdraw/border.c, sys/src/libdraw/menuhit.c
+ Now we can draw 3D borders
+ We can change default menu colors.
=> New functions to libdraw

sys/src/cmd/build.json, sys/src/cmd/jay/config.c, sys/src/libmemdraw/draw.c
- Adding jay to general build process
=> Fix for memdraw

.travis.yml
=> Upgrading travis to gcc7

README.md
=> readme: update read me to reflect the process made #775 by Sevki

README.md
=> Adjusting date one more time in readme

sys/include/jay.h, sys/src/cmd/cmd.json, sys/src/cmd/jay/config.c, sys/src/cmd/jay/dat.h, sys/src/cmd/jay/data.c, sys/src/cmd/jay/fsys.c, sys/src/cmd/jay/jay.c, sys/src/cmd/jay/panel.c, sys/src/cmd/jay/scrl.c, sys/src/cmd/jay/smenu.c, sys/src/cmd/jay/time.c, sys/src/cmd/jay/util.c, sys/src/cmd/jay/wctl.c, sys/src/cmd/jay/wind.c, sys/src/cmd/jay/xfid.c, sys/src/libjay/config.c, sys/src/libjay/fns.h, sys/src/libjay/label.c, sys/src/libjay/libjay.json, sys/src/libjay/panel.c, sys/src/libjay/utils.c, sys/src/libjay/widget.c, sys/src/libjay/window.c, sys/src/libjay/wlist.c, sys/src/libs.json, sys/src/test/build.json, sys/src/test/labels.c
First pieces of the future libjay. This will allow to improve the Jay environment and will allow to develop graphic applications much faster than now. It is functional but still has a lot of work to do.
=> Libjay init

sys/src/9/amd64/dat.h, sys/src/9/amd64/fpu.c, sys/src/regress/fpuexcept.c, sys/src/regress/fpunote.c, sys/src/regress/fpustate.c
- Eager saving of state
- No x87 exception handler
- No restriction on FPU use in note handlers
- A few regression tests for the FPU
Missing
- More tests
- More modern features (e.g. XSAVE)
- Probably also some fundamental things missed, but hopefully not too many
=> First attempt at simpler, eager FPU state saving

sys/src/cmd/acme/text.c, sys/src/cmd/zenith/text.c
=> Solved issue "weird indentation behavior with acme" #518

sys/src/9/386/i8042.c
Now we can process the keyboard events in kbin.
This only solves the keyboard problem. We need to review the mouse problem.
=> Solving USB keyboard problem in #452

sys/src/cmd/ext2srv/ext2subs.c
=> Fixed problem when an ext2 partition is mounted

util/SYSLINUX
=> Fixing util/SYSLINUX howto

sys/doc/n9p.ms
It's stateless and that's a good thing.
=> straw man new protocol

util/GO9PIMG
=> Yet another GO9P* script - GO9PIMG runs from a qcow2 img

sys/include/atomic.h, sys/src/9/amd64/sdiahci.c
=> Add atomic store and load. Seems we need it

sys/src/9/port/elf64.c
=> Adding headers to elf64.c

util/syslinux.go
Very simple first pass, lots to do yet.
=> WIP: syslinux: add syslinux script.

amd64/include/gcc-8.json
=> Adding GCC 8

util/GO9PIMGUSB
=> Added GO9PIMGUSB to test Harvey in a USB device

rc/bin/termrc
=> Remove duplicate/non-existant devs from termrc

.travis.yml
=> Upgrading travis for clang 6

sys/src/9/amd64/build.json
=> Removing useless internal from ramfs

.travis.yml, amd64/include/clang-6.0.json, sys/src/9/amd64/build.json
=> Restoring boot in ramfs

rc/bin/termrc
=> Aesthetic issue about rm

amd64/include/cflags.json, amd64/include/klib.json, sys/src/9/amd64/core.json, sys/src/9/amd64/inith.json, sys/src/libacpi/acpica/acpiflags.json
For those OSes that has it enabled by default
=> Disabling stack protector

rc/bin/tests/runall, rc/bin/tests/runalltofile, sys/src/regress/fpuexcept.c, sys/src/regress/fpunote.c, sys/src/regress/fpustate.c
Only runs 2 tests so far, can add more/improve script over time
=> Run all (some) regression tests

README.md
=> Some updates to the Readme file

rc/bin/termrc
=> Minor cleanups.

sys/src/9/amd64/inith.json
=> Ensure init.h regenerated every time

util/src/harvey/cmd/build/build.go
=> Revert previous change to build.go for now - should fix build

rc/bin/cpurc
=> Remove cpurc warning

rc/bin/shutdown
=> Adding an rc front script for shutdown

sys/src/regress/amd64/args.c, sys/src/regress/amd64/build.json, sys/src/regress/build.json
=> Fix args test, move to regress/amd64 folder

sys/src/9/amd64/archamd64.c
=> Adding some CPUs

sys/src/9/amd64/archamd64.c
=> Add Intel Atom to cpuidhz

sys/src/cmd/rio/rio.c, usr/harvey/bin/rc/riostart, usr/harvey/lib/profile
=> bring up stats and terminal window on term startup

util/src/harvey/cmd/build/build.go
=> build can handle source files with > 1 letter extensions

util/src/harvey/cmd/build/codegen.go
(Requires bootstrap to be re-run)
=> Set read/write segment flags for bss and shared segments

sys/src/9/port/sysfile.c, sys/src/regress/libc/readoffset.c
=> pread shouldn't update dev offset

sys/include/tos.h, sys/src/9/amd64/fns.h, sys/src/9/amd64/syscall.c, sys/src/9/amd64/trap.c, sys/src/9/port/execaout.c, sys/src/9/port/port.json, sys/src/9/port/portdat.h, sys/src/9/port/sysproc.c, sys/src/9/riscv/trap.c, sys/src/libc/port/malloc.c, sys/src/libthread/exit.c, sys/src/libthread/id.c, sys/src/libthread/sched.c, sys/src/regress/misc/tos.c, sys/src/test/pid.c
Bring a.out format back. Go is not going to be flexible on this point.
Feel free to tell me how to help make this compile.
e.g. where is l2be again? I forget.
Signed-off-by: Ronald Minnich <rminnich@gmail.com>
=> The empire strikes back

sys/src/9/amd64/syscall.c
Plan 9 is a 32-bit kernel. This is reflected in the
seek that Go uses, in which the first param is a
uint64_t.
if up->plan9 is set, check the system call number and,
if it is SEEK, modify behavior:
o use first arg as a uint64_t and verify
o use args 1-x instead of 0-x
o story ar0.p into the pointer on return.
This fixes Go environment walking among other things,
and enabled the u-root rush shell to work.
=> Fix seek for Plan 9 binaries

sys/src/9/amd64/sdiahci.c, sys/src/cmd/aux/vga/clgd546x.c, sys/src/cmd/aux/vga/radeon.c, sys/src/libc/port/malloc.c, sys/src/libusb/serial/ftdi.c
=> Clang 9 and higher complaining

sys/src/9/amd64/archamd64.c
This is on an x230 laptop with coreboot.
This allows it to boot.
=> Fix msr GPF for cpu signature 0x000306a0

README.md
Signed-off-by: sevki <s@sevki.org>
=> readme: change the build status badge

sys/src/9/386/uarti8250.c
This has been a pain for years, finally fixed.
=> Change default 9600 baud to 115200

sys/src/9/amd64/acpi.h, sys/src/9/amd64/asm.c, sys/src/9/amd64/devacpi.c, sys/src/9/amd64/fns.h, sys/src/9/amd64/multiboot.c
clean up rsdp parsing. Vendors don't follow ACPI rules, there's a shock.
=> Fix multiboot args

.github/workflows/harvey.yml, CONTRIBUTING.md, README.md, sys/man/2/keyboard, sys/man/2/mouse, sys/src/cmd/cmux/dat.h, sys/src/cmd/fossil/archive.c, sys/src/cmd/fossil/disk.c, sys/src/libacpi/acpica/components/utilities/utresdecode.c, sys/src/libdraw/init.c, sys/src/liboventi/server.c
Signed-off-by: sevki <s@sevki.org>
=> rename master to main

bootstrap.sh
we have a new `main` branch now - my bad, that should have been the target 🙃
=> sync to main branch

sys/src/9/386/uarti8250.c, sys/src/9/boot/boot.c
It's a hack but it's working and will let us debug on atomic pi, apu2, and others.
The uart is enabled by forking a child in boot.c and having it open #t/eia0.
As long as that process is around the uart is polled. Kill it and polling stops.
=> get serial console finished.

sys/src/9/port/taslock.c
http://9legacy.org/9legacy/patch/9-taslock-unlock.diff
from 2016.
=> tasunlock: add extra coherence (Richard Miller)

sys/src/9/amd64/main.c
This 5 year old weird problem is now fixed.
=> Remove zero'ing of bss, as it wipes out sys and entrym

sys/src/9/amd64/ether82563.c
Based on code from 9 front, covered by MIT license.  No sign of any different licenses specified in the commits for this file.
The code doesn't exactly match the 9front version, sicne the two codebases have diverged, but the behaviour should.
Tested on an Asus Maximus Hero VIII, based on Intel Z170 chipset.
=> Add support for Intel i219 eth cards

sys/src/9/amd64/ether82563.c
=> add potentially hacky switch which makes apu2 ethernet work

sys/src/cmd/mount.c
We added the ability to use mount devices other than 'M' 5 years ago.
Somehow this command never reflected it or it was lost in the
great source cleanup a few years back.
If the user specifies -M with an option, e.g. 9, that will be
used as the mount device. A -M with 9 specifies 9p2000.L; it's been
in there for 4 years. It has issues but might give us a path to
easily using ipfs and hugelgupf/p9 without changing those systems.
It is claimed to work with the qemu 9p2000.L server.
Also, do a minor cleanup. The name 'aname' was used in amount0, but
its name in main was 'spec', doubly confusing. aname is the attachname
to present to the server, so use that everywhere.
=> mount: allow specification of mount device, small cleanup

sys/src/9/amd64/ether82563.c
originally from the plan9front file of the same name.
=> ether82563: load mac address from invm for i210

bootstrap.sh, go.mod, go.sum, util/ci.sh
=> Fix go deps to most recent harvey go + most recent working u-root

sys/src/9/port/devramfs.c
no rename or user change yet.
192.168.0.7# 192.168.0.7# touch '#@/x'
192.168.0.7# chmod 444 '#@/x'
192.168.0.7# ls -l '#@/x'
--r--r--r-- @ 0 harvey harvey 0 Feb  7  2006 '#@/x'
192.168.0.7# chmod 777 '#@/x'
192.168.0.7# ls -l '#@/x'
--rwxrwxrwx @ 0 harvey harvey 0 Feb  7  2006 '#@/x'
=> devramfs: partially implement wstat

sys/src/9/port/devramfs.c
the read was not doing the right # of bytes.
Debug prints are now disabled.
=> Fix embarrasing errors in ramfs

sys/src/9/port/devramfs.c
=> devramfs: fix wstat

sys/src/9/port/devramfs.c
Go gets up set if you return fewer bytes written than it
asked for.
devramfs write will now write as much as it is asked to write.
=> Fix devramfs write for Go

sys/src/9/port/execaout.c
=> get rid of annoying aoutldseg print

sys/src/9/port/devramfs.c
devramfs was built with the kernel name length of 28 characters.
Allow longer names by dynamically allocating the name.
This now works and did not before.
192.168.0.7# cd '#@'
192.168.0.7# echo -n hi > 0123456789012345678901234567890
192.168.0.7# ls -l
--rw-rw-rw- @ 0 harvey harvey 2 Feb  7  2006 0123456789012345678901234567890
192.168.0.7# cat 0*
hi192.168.0.7#
=> Fix devramfs names

.github/workflows/harvey.yml
=> CI: retrieve keys for LLVM repo

sys/src/9/amd64/main.c
harvey does not boot with ease on many modern x86 CPUs yet.
Add a post() function for main to provide copious debug
output, if a static variable is set.
=> amd64/main.c: add a post function to improve bringup debugging

bootstrap.sh, go.mod, go.sum
=> Update bootstrap to fetch latest go cmds, also tidy bootstrap messages a bit

sys/src/9/386/ether8169.c, sys/src/9/386/etherigbe.c, sys/src/9/386/etherm10g.c, sys/src/9/amd64/ether8139.c, sys/src/9/amd64/ether82563.c, sys/src/9/amd64/io.h, sys/src/9/amd64/sdata.c, sys/src/9/amd64/sdiahci.c, sys/src/9/amd64/usbuhci.c
There are many, many more lurking in the code.
=> Remove a host of 32-bit assumptions

.clang-format, sys/src/9/amd64/main.c
Code has gotten inconsistent.  Start to clean it up.
=> clang-format: start to clean up code

sys/src/9/amd64/mmu.c
It didn't terminate correctly.
=> Clean up mmuwalk.

sys/src/9/port/devramfs.c
It will now be more informative about what failed and why.
=> The ramfs error messages are misleading; fix them

.gitignore
Signed-off-by: sevki <s@sevki.org>
=> gitignore: add compile_commands.json

rc/bin/urootrc
=> Decompress and unpack uroot cpio archive using pipe

bootstrap.sh
=> Always update go dependencies in bootstrap

sys/src/9/amd64/devacpi.c
Harvey wasn't booting on a 4GB apu2 (see below, note ax register compared to memory map). Pull #1043 (commit 71f450f) removed a bunch of vmap calls from devacpi.c. Upon restoring them, Harvey boots again.
```
Harvey
magic 0x2badb002 pmbi 0x9cee0
flags 0x24d
cmdline <http://192.168.0.92/harvey.32bit -n service=cpu nobootprompt>
Memory (1)      0x0000000000000000 0x000000000009fc00 (654336)
Memory (1)      0x0000000000100000 0x00000000cfe89000 (3487076352)
Memory (1)      0x0000000100000000 0x000000012f000000 (788529152)
bootloadername <iPXE 1.0.0+ (ebf2)>
pamap: {
[0x0000000000000000, 0x0000000000001000) KRDONLY  (4096)
[0x0000000000001000, 0x0000000000080000) MEMORY   (520192)
[0x0000000000080000, 0x00000000000a0000) KRDWR    (131072)
[0x00000000000a0000, 0x00000000000c0000) DEV …
```
=> Fix panics due to bad acpi memory accesses.

sys/src/9/amd64/trap.c
This helps show more logging context when something goes wrong at boot and you have no serial
=> Pack dumped regs more tightly

amd64/include/u.h, sys/src/cmd/aux/i2c/tpm/tis.c, sys/src/cmd/aux/i2c/tpm/tpm.c, sys/src/cmd/iozone/iozone.c, sys/src/cmd/iozone/libasync.c, sys/src/cmd/iozone/pit_server.c, sys/src/games/mp3dec/decoder.c, sys/src/games/mp3enc/pcm.c
=> Replace ssize_t with isize

amd64/include/u.h, riscv/include/u.h, sys/src/9/port/portdat.h, sys/src/9/riscv/stdint.h, sys/src/cmd/lex/sub2.c, sys/src/cmd/tbl/t5.c
=> replace intptr_t with isize

sys/include/usb/ums.h
=> Fix crash with usb disks

sys/src/IMPORT.md
=> Define rules for importing code.

sys/src/cmd/frontusb/audio/build.json, sys/src/cmd/frontusb/build.json, sys/src/cmd/frontusb/cam/build.json, sys/src/cmd/frontusb/disk/build.json, sys/src/cmd/frontusb/ether/build.json, sys/src/cmd/frontusb/joy/build.json, sys/src/cmd/frontusb/kb/build.json, sys/src/cmd/frontusb/lib/build.json, sys/src/cmd/frontusb/ptp/build.json, sys/src/cmd/frontusb/serial/build.json, sys/src/cmd/frontusb/usbd/build.json
First pass - will almost certainly need more change.
=> frontusb: add initial build.jsons

sys/src/cmd/frontusb/cam/ctl.c, sys/src/cmd/frontusb/disk/scsireq.c, sys/src/cmd/frontusb/ether/asix.c, sys/src/cmd/frontusb/ether/aue.c, sys/src/cmd/frontusb/ether/ether.c, sys/src/cmd/frontusb/ether/lan78xx.c, sys/src/cmd/frontusb/ether/smsc.c, sys/src/cmd/frontusb/ether/url.c, sys/src/cmd/frontusb/kb/kb.c, sys/src/cmd/frontusb/serial/ch340.c, sys/src/cmd/frontusb/serial/ftdi.c, sys/src/cmd/frontusb/serial/serial.c, sys/src/cmd/frontusb/serial/serial.h, sys/src/cmd/frontusb/serial/silabs.c, sys/src/spatches/patch_scalar.cocci
`Signed-off-by:` Graham MacDonald <grahamamacdonald@gmail.com>
=> frontusb: convert uint -> u32, update cocci

sys/src/cmd/frontusb/audio/build.json, sys/src/cmd/frontusb/build.json, sys/src/cmd/frontusb/cam/build.json, sys/src/cmd/frontusb/disk/build.json, sys/src/cmd/frontusb/ether/build.json, sys/src/cmd/frontusb/joy/build.json, sys/src/cmd/frontusb/kb/build.json, sys/src/cmd/frontusb/ptp/build.json, sys/src/cmd/frontusb/serial/build.json, sys/src/cmd/frontusb/usbd/build.json
=> frontusb: build json fixes (build lib first)

sys/src/9/port/devshr.c
added mit license to top of file, with 20XX changed to 2021
=> devshr: initial import of devshr from 9front

.github/workflows/harvey.yml, build/.gitignore, build/command.bash, build/make.bash
that boots from the 9legacy ISO and runs a command. For use
as a jumping-off point.
=> Implement some really, really basic Github Actions stuff

.github/workflows/harvey.yml, build/command.bash
Now we're booted into an environment with all the tools we need to build, and the source we intend to build from in /n/harvey. Baby steps.
=> Make the workflow install & run ufs, then mount it and do an ls.

.github/workflows/harvey.yml, build/command.bash
=> Run go command in command.bash, check version

build/build.bash
=> Add --format flag to tar invocation so we can be sure we use ustar

sys/src/libc/mkfile
=> SPARC is dead. Remove it

sys/include/bio.h, sys/man/2/bio, sys/src/libbio/binit.c
Required for git9.
From plan9port via 9front (commit 035aacf6f5c23f0513e240046818ef203e8d87cb).
=> Add Bfdopen() to libbio

sys/src/cmd/walk.c
=> walk: remove Bfdopen now that it's been added to libbio

sys/src/cmd/mclock.c
This required *NO* changes for harvey. It's a model of how to write
portable graphics code.
There's an interesting back story here. In 1975 or so, at University of
Delaware, there was competition between the advocates of the PLATO
system, (wikipedia plato cdc), which ran on very expensive
supercomputers, and the RSTS/E system, that ran on a 100x cheaper PDP 11
minicomputer.
Roughly, looking at relative money and power, the PLATO team were the
suits, and the minicomputer guys were the rebel alliance. At least
that's how it seemed to us at the time ...
Much was made of the PLATO system's graphics, which were a big deal at
the time. My then advisor, Dr. David M. Robinson, believed the
minicomputer could equal the interactive performance of the CDC Cyber
mainframe. At the time we had the …
=> Add the famed mclock.

build/build-go.sh, build/scripts/build
=> clean up some stuff after compilation to keep image size down

build/build-usb.bash, build/build.bash, build/scripts/build, dist/replica/plan9.proto
=> more adjustments to build scripts

sys/src/9/pc/ether82563.c
Lightly modified.  This seems to work with the ethernet
interfaces on the Supermicro M11SDV-8C-LN4F's in my file
and CPU servers.
=> Import ether82563.c from 9front

sys/src/cmd/acme/exec.c, sys/src/cmd/sam/io.c
Bring in two of Russ's changes from plan9port, making minor fixes to both sam and acme.
Note I added plan9port as a remote to my Harvey repository, and just cherry-pick'ed these commits.
=> Merge in recent changes from plan9port

build/RUNCOREBOOT
=> Add runcoreboot script so we can experiment with UEFI failure

build/scripts/build, build/scripts/usb, sys/src/9/boot/boot.c, sys/src/9/mkfile, sys/src/mkfile
=> Make the usb build script use nboot.

sys/src/9/pc/trap.c, sys/src/9k/k10/trap.c
I believe this fixes what David observed.
=> rdmsr: Don't panic on user GPF.

sys/src/9k/k10/trap.c
=> Fix 9k build problem with gpf vector
