Harvey-OS/harvey

sys/include/libc.h, sys/src/cmd/dossrv/xfile.c, sys/src/cmd/file.c, sys/src/libc/port/charstod.c, sys/src/libc/port/strtod.c
The strtoul pointer casts are set wrong. There are more strtoXY casts
set wrong. These will all get a separate CR. Issue #14.
=> The strtoul pointer casts are set wrong.

sys/src/9/386/devether.c
The index -1 was supposed to key a search or ISA cards. ISA is dead. I removed the
code but missed the probe of -1. Nothing broke.
This panic was not found until we started building with clang and the kernel
panic'ed. We ran for a year with this bug.
=> Remove the probe for ISA cards.

sys/src/9/amd64/clang.json
Until we figure out how to special-case flags for compilers (or we get that in the new build tool)
just use this file for building the kernel. We don't want xmm usage in the kernel for now.
To use
CC=clang build sys/src/9/amd64/clang.json
=> clang: add sys/src/9/amd64/clang.json

sys/src/9/port/page.c
The expression could never be nil. The original was testing against
the value of p in the lock, i.e. whether another process wanted to use
the pool and we got there first.
This is pretty amazing stuff, in that it works at all, but the use of anon
struct members made it even more confusing. Overall, I think they're a bad deal.
=> Fix an error resulting from the deanon work.

sys/man/1/ratrace, sys/src/cmd/ratrace.c
While debugging the gdbserver it became essential to have a -o switch.
=> ratrace: add a -o switch

amd64/include/cflags.json
Until we move the Harvey's Plan 9-based floating point save/restore code from 1991 to 2016,
we have to disallow implicit floating point, because otherwise clang generates
code that uses xmm registers, some of it in note handlers, and the kernel will
kill the process. This was causing bad trouble for usbd among other things.
The fix is to do what we did in Akaros:
- disable any use of the x87
- move to xsaveopt and eager save/restore
But for now, this fixes the problem, at a cost in performance.
usbd no longer explodes in the timeout handler (which is a note handler).
Some amount of study of what we did in Akaros will show the way.
=> clang: force no implicit float in user mode for now

clean.json
It now blows away $ARCH/bin without thinking hard (because, stupidly, amd64/bin includes
some rc scripts, i.e. not binaries -- wtf?) and all the .a's in lib. Then, to undo
any possible damage, it does a checkout of $ARCH/bin
=> Fix the clean rule

sys/src/cmd/build.json
Acid was mistakenly added to the build even thought it still requires plan 9
extensions. This broke clang building.
=> Remove acid from the build.

util/src/harvey/cmd/build/build.go
This was so simple I don't know why I did not do it long ago.
Now if you goto error emacs will find it, as build outputs entering and leaving
directory info.
=> build: make it emacs friendly by showing directories

aarch64/include/u.h, aarch64/include/ureg.h
Start of the aarch64 port: add basic types, register
definitions.
=> Start of aarch64 port: Add u.h, ureg.h.

util/src/harvey/cmd/build/build.go
This should fix BSD issues, and it's the right way
to do an static compilation.
=> Fixing order of elements for ld

sys/src/9/amd64/build.json, sys/src/9/amd64/sdata.c
The atadrive function was declaring a local 512 byte buf, i.e. a
stack variable. Big arrays like this on kernel stack are almost always
a bad idea. In this case we were getting a page fault on NULL while probing.
I'm pretty sure this function is single threaded, i.e. only one invocation
is ever active at a time. So I just made buf[] static. The sdata panics
promptly ceased.
If you ever want to make this function reentrant you'll need to use malloc to
allocate buf[] and be sure to free it on all the (many) exits.
=> amd64/sdata.c: Make buf[] in atadrive() static.

sys/src/9/amd64/BUILD, sys/src/BUILD, sys/src/cmd/BUILD
blaze is so much smarter than our old build we can just do it this way.
One issue: this fails with a very unclear diagnostic, I have to run it twice.
Help?
=> blaze: just make the kernel depend on //sys/src/cmd:cmds

sys/src/cmd/zenith/acme.c, sys/src/cmd/zenith/build.json, sys/src/cmd/zenith/cols.c, sys/src/cmd/zenith/dat.h, sys/src/cmd/zenith/ecmd.c, sys/src/cmd/zenith/exec.c, sys/src/cmd/zenith/fns.h, sys/src/cmd/zenith/fsys.c, sys/src/cmd/zenith/look.c, sys/src/cmd/zenith/rows.c, sys/src/cmd/zenith/text.c, sys/src/cmd/zenith/util.c, sys/src/cmd/zenith/wind.c, sys/src/cmd/zenith/xfid.c, sys/src/cmd/zenith/zenith.init, sys/src/libc/port/malloc.c, usr/harvey/lib/zenith.init
See zenith.init for details - apart from the existing keyboard shortcuts, I've added:
^s^x to execute the current line
^s^f to display a fortune (just to test the external command keymapping)
^s^l to run ls -l in the current directory.
There's a minor bug with up/down keys going over a blank line, but I wanted to get this change in before I looked at it.
=> Added customisable keymapping to zenith

sys/src/9/aarch64/BUILDME, sys/src/9/port/elf64.c
arm64 -> aarch64 in elf64.c, and the toolchain prefix in
BUILDING should be 'aarch64-none-eabi-'.
=> Name changes for aarch64.

sys/src/9/amd64/mp.c
The code assumes, from the earliest stages, that apicbase
has been set. Right now, it's only set in the mp table parser.
The result is that there are obscure failures if no _MP_ is found.
We need to drag this code base into the third millenium but at least
for now make an error that is useful, instead of just a panic on
referencing address 0x20.
THINK CAREFULLY BEFORE YOU LGTM THIS ONE.
But it at least gives me a comprehensible error on coreboot on the thinkpad.
=> Panic if there is no MP table

sys/src/9/amd64/core.json, sys/src/9/port/devramfs.c, sys/src/libc/port/pool.c, sys/src/libmach/8db.c, sys/src/libmach/machdata.c, sys/src/libmach/sym.c, sys/src/libmemdraw/draw.c, sys/src/libmemdraw/drawtest.c, sys/src/libsec/port/md5pickle.c, sys/src/libusb/audio/audio.c, sys/src/libusb/audio/audiosub.c, sys/src/libusb/ether/asix.c, sys/src/libusb/ether/ether.c, sys/src/libusb/kb/hid.c, sys/src/libusb/kb/kb.c, sys/src/libusb/lib/devs.c, sys/src/libusb/lib/dump.c, sys/src/libusb/lib/fs.c, sys/src/libusb/serial/ftdi.c, sys/src/libusb/serial/prolific.c
Restoring -Werror for kernel build
(secondary: replacing memcpy in port/devramfs for memmmove
to avoid warning in kernel build)
=> fixfmt: Last cleaning of %u modifier in libs

sys/src/9/386/pci.c, sys/src/9/amd64/devacpi.c, sys/src/9/amd64/fns.h
Remove $PIR support, that table's been bogus for years on most systems.
Many vendors use the same (wrong) one for many mainboards.
More ACPI fun!
=> ACPI: continue the code massacre.

sys/src/9/386/pci.c, sys/src/9/amd64/devacpi.c, sys/src/9/amd64/io.h
The pci intp pin is far more useful than the intl, which seems
to be tied tightly to 8259 mode.
=> ACPI: further changes, both to pci, and ACPI

sys/src/lib.json, sys/src/libc/port/reallocarray.c
In sys/src/lib.json: use 'rm -f' when removing object files.
In sys/src/libc/port/reallocarray.c: Actually make this build
under Harvey. :-)
=> Fix reallocarray and use 'rm -f' when cleaning.

sys/src/9/amd64/sdata.c, sys/src/9/port/devdraw.c, sys/src/9/port/devsd.c
The errors found in sdata.c were potentially responsible for kernel panics.
Signed-off-by: Aaron <aaron@ahud.me>
=> Fix compiler errors found by clang 3.8.0-1

util/GO9PRUN
Use the HARVEY variable so that we don't have to be any
particular place to run it correctly.
Add a shebang (#!/bin/bash) and set -e so some errors
get caught.
Add a port forward for 5356 so we don't get ridiculous delays on
start. CPU servers don't run auth servers anyway, but this cpu
server would hang on the auth server.
=> Fix GO9PRUN

sys/src/9/386/pci.c, sys/src/9/port/devpci.c
This patch should fix the symptoms described in the issue #231. 
Resulting output from pci:
0.0.0:  brg   06.00.00 8086/29c0   0
0.1.0:  vid   03.00.00 1b36/0100  10 0:f4000000 67108864 1:f8000000 67108864 2:fc090000 8192 3:0000c281 32
0.10.0: virtio-balloon 00.ff.00 1af4/1002  11 0:0000c301 32
0.11.0: virtio-disk    01.00.00 1af4/1001  11 0:0000c201 64 1:fc099000 4096
0.2.0:  net   02.00.00 10ec/8139  11 0:0000c001 256 1:fc092000 256
0.3.0:  virtio-net     02.00.00 1af4/1000  11 0:0000c2a1 32 1:fc093000 4096
0.31.0: brg   06.01.00 8086/2918   0
0.31.2: disk  01.06.01 8086/2922  10 4:0000c321 32 5:fc09a000 4096
0.31.3: smb   0c.05.00 8086/2930  10 4:0000b101 64
0.4.0:  virtio-9p      00.02.00 1af4/1009  10 0:0000c101 64 1:fc094000 4096
0.5.0:  virtio-9p      00.02.00 1af4/1009  10 …
=> Use %.8llx in devpci.c and pci.c: this fixes (on the surface) issue

sys/src/9/amd64/BUILD, sys/src/9/amd64/amd64coreboot.json, sys/src/9/amd64/build.json
=> sdata: remove sdata.c from the build.

amd64/include/cflags.json, sys/src/9/amd64/apic.c, sys/src/9/amd64/core.json, sys/src/9/amd64/ioapic.c, sys/src/9/amd64/mp.c
This correctly invoked the version compilers (e.g. clang-3.7) with
the option, but it only seemed to for no-implicit-float with
CC=clang
I have no idea but I hope mkx will allow selection of these
flags for different compilers.
=> clang: add more compiler names that need -mno-implicit-float

sys/src/libc/port/reallocarray.c
We saw a problem in devacpi.c when realloc was called
to create a zero-length array: it returned a nil pointer,
not a pointer to a zero-length array, which confused the caller.
Consider the difference between:
char *s = "";
char *s = nil;
The first is a pointer to a zero-length string, the second
a NULL pointer. We want realloc to implement the first,
rather than the second.
=> realloc: handle zero-length arrays.

amd64/include/cflags.json, amd64/include/klib.json, sys/src/9/amd64/core.json, sys/src/cmd/fossil/check.c, sys/src/lib9p/req.c, sys/src/lib9p/srv.c, sys/src/libauth/auth_getkey.c, sys/src/libmemlayer/draw.c, sys/src/liboventi/server.c
Added -Wno-frame-address to avoid errors about
__builtin_frame_address in:
- libc/port/getcallerpc.c
- libc/port/malloc.c
And related in kernel and cmd.
Unfortunately, clang doesn't recognize this warning supress option,
instead it has -Wno-address. Suggestions for tweaking old build and new
build tools are welcome.
NOTE: if/else statements indentation is now a warning in case
{} would be missing.
=> Updating code to be able being built by gcc 6

sys/src/9/amd64/asm.c, sys/src/9/amd64/devacpi.c, sys/src/9/amd64/ioapic.c, sys/src/9/amd64/main.c, sys/src/9/amd64/mpacpi.c, sys/src/9/port/devcons.c, sys/src/9/port/devcoreboot.c, sys/src/9/port/devtab.c, sys/src/9/port/portfns.h
add kmprint, which is like print but only goes to the
kmesg buffer, i.e. does not pollute the console.
Use kmprint and just reduce the amount of junk printed
so people can see their boot messages.
=> QUIET: quiet things down

sys/src/libc/fmt/dofmt.c, sys/src/regress/build.json, sys/src/regress/fmt.c
For a long time, this code sequence:
unsigned long x = 0xfeefd000deadbeef;
seprint(buf, buf+sizeof(buf), "%.2X", x);
print("%s\n", buf);
would result in this
-21524111
which is not at all what we want.
With this fix, they now result in this:
DEADBEEF
This change includes a simple test for testing formatting, which
we should grow over time: fmt.c
=> format: fix longstanding formatting bug

sys/include/libc.h, sys/src/libc/9sys/qlock.c, sys/src/libc/9sys/read.c, sys/src/libc/9sys/write.c, sys/src/libc/port/lock.c
We don't put names in .h files. If we did, we'd have a lot
of names in here.
=> sys/include/libc.h: remove a name

sys/src/cmd/acpi/irq.c
This is *A* bug, but not *the* bug.
=> ACPI: only scan two things from irqmap, not 3.

sys/src/sysconf.json
In the begining, we had hybrid binaries that run under linux and plan 9.
Nobody really used or needed them. For Go, it's better to just use Plan 9
numbering. So, go back to Plan 9 numbering.
=> nohybrid: revert system call numbering to Plan 9

sys/src/libacpi/acpica/acpiflags.json
Should work on all systems using the FreeBSD kernel, only
certain for FreeBSD.
Signed-off-by: Aaron Hudson <aaron.hudson@student.nmt.edu>
=> Add acpi flag to disable GCC macros on BSD systems

sys/src/9/port/syscallfmt.c
We should use syserrstr, not errstr.
=> Fix which errstr is used for syscallfmt.

sys/src/9/amd64/syscall.c
The line was likely left by mistake.
=> Remove line 335 in syscall.c which caused unneeded console output

sys/include/virtio_ring.h, sys/src/9/386/pci.c, sys/src/9/port/devpci.c
This reverts commit db0ccedae86f62178dc57f41b289fd0f38a18bb1.
We need to bring the external code in a bit more staged.
First, bring the files in with the source (kernel) and git ref
of where they're from. Then start changing them.
Conflicts:
sys/src/9/386/pci.c
sys/src/9/amd64/virtio_ring.h
sys/src/9/port/devpci.c
=> Revert "Bring in the virtqueue definitions from the virtio spec 1.0. Make sure"

util/src/harvey/cmd/build/paths.go
build was checking if you have HARVEY set and, if so, *not*
adding util/ to your PATH. Fix that because it caused weird
problems.
=> Remove weird $HARVEY check in build

sys/src/libacpi/harvey.c
This is not documented in the ACPICA spec but the
returned pointer to bytes read can be nil.
=> acpi: accomodate null pointers in ApciOsGetLine

sys/src/9/386/pci.c
Allow scanning of virtio-pci devices with CCRB == 0x00.
=> Restore part of PR #180 reverted in omission.

sys/include/virtio_lib.h, sys/src/9/port/port.json, sys/src/9/port/virtio_lib.c
This is the abstract virtio code extracted from former devvq. One addition needs to be done elsewhere: the initvdevs function (find and initialize all virtio devices) used to be called from devvq's devinit method. Since we no longer expose all queues via a device, there should be place in Harvey's initialization where such function can be called.
=> Initial commit of the virtio library.

sys/src/9/riscv/core.json, sys/src/9/riscv/fns.h, sys/src/9/riscv/main.c
A lot more is working. We can link with klibc and use memset.
We can set up initial mach pointer and stack in C, not assembly, which
avoids lots of nastiness.
Next step: split amd64/asm.c in arch and port parts, so we can use that code.
=> riscv: booting to a bsp boot function

sys/src/9/aarch64/BUILDME.trivial, sys/src/9/aarch64/cpu.json, sys/src/9/aarch64/l.S, sys/src/9/aarch64/main.c, sys/src/9/aarch64/trivial.json
Where 'kernel' is defined as a single 'WFI' instruction.
=> Compile minimal aarch64 kernel.

aarch64/include/mach_acpi.h
Add ACPI-types compatibility file for building ACPI on ARM.
ACPI is pretty much x86-specific, but it's a long-standing
Plan 9 tradition that one can build everything everywhere.
=> Add ACPI-types compatibility file for building ACPI on ARM.

sys/src/cmd/aux/console/utils.c, sys/src/cmd/gdbserver/aarch64.S, sys/src/cmd/gdbserver/regsaarch64.c, sys/src/cmd/zenith/util.c, sys/src/libc/aarch64/ainc.S, sys/src/libc/aarch64/argv0.c, sys/src/libc/aarch64/build.json, sys/src/libc/aarch64/getcallerpc.S, sys/src/libc/aarch64/getcallstack.S, sys/src/libc/aarch64/main9.S, sys/src/libc/aarch64/notejmp.c, sys/src/libc/aarch64/setjmp.c, sys/src/libc/aarch64/sqrt.c, sys/src/libc/aarch64/tas.S, sys/src/libthread/aarch64.c
Implement (or copy from another architecture) most of the
bits required for building libraries and applications for
aarch64.  The system more or less builds now.
I'm sure there are some bugs in this code: see, for example,
libc/aarch64/main9.S: this is the "get to build" stage.  The
next stage is "make work."
=> Various bits of aarch64 code to support ARM64.

sys/src/libc/aarch64/main9.S
Want your TLS? It's nil kid; that's your TLS.
(This just makes regress build. Now all of Harvey
builds for aarch64.)
=> Skeletal 'gettls0' for aarch64.

sys/src/libc/riscv/build.json, sys/src/libc/riscv/getcallerpc.c, sys/src/libc/riscv/getcallstack.c
Implement getcallerpc, getcallstack, and gettls0 for
riscv.  Note, I don't have a riscv toolchain set up;
hopefully Ron can test this out.
=> riscv: Bring in latest portability interfaces.

sys/src/libc/port/cistrcmp.c, sys/src/libc/port/runestrcmp.c, sys/src/libc/port/strcmp.c
Make strcmp and cistrcmp more straight-forward.  I believe
the originals were correct, but these are more obvious.
Note: Please review these *very* carefully.
=> Rewrite cistrcmp and strcmp.

amd64/include/cflags.json, amd64/include/klib.json, sys/src/9/amd64/core.json
In lieu of coming up with a cleaner mechanism,
add yet another compiler pathname to these files.
We need a better way.
=> Add another tool path to these build rules.

rc/bin/termrc, sys/include/virtio_lib.h, sys/src/9/386/pci.c, sys/src/9/amd64/build.json, sys/src/9/port/devvcon.c, sys/src/9/port/port.json, sys/src/9/port/virtio_lib.c
Somewhat working virtual console. To test (neither works completely, but shows that communication is working), create 2 virtual serial consoles:
```
-device virtio-serial-pci,max_ports=1 \
-device virtconsole,chardev=vc02 \
-chardev socket,id=vc02,path=/tmp/vc02 \
-device virtio-serial-pci,max_ports=1 \
-device virtconsole,chardev=vc00 \
-chardev socket,id=vc00,path=/tmp/vc00,server,nowait \
```
Note that virtio-serial-pci is specified twice. I decided not to complicate the logic with the multiport feature support, but this means that for several consoles we need several buses (which is provided by virtio-serial-pci). Only port 0 is supported, which means that only "virtconsole" can be used (not sure if there is any difference between virtconsole and virtserialport).
Run ufs on one of …
=> Virtual serial console somewhat working.

sys/src/9/port/devvcon.c
Disable calls to functions that panic Harvey at boot.
=> Disable panicy functions in devvcon.

amd64/include/klib.json, sys/src/9/amd64/core.json
It failed for me in Debian Testing
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=77464
With this kernel builds again. Please, take it to bldy.
=> GCC 6.2 has --enable-default-pie in Debian

util/GO9PCPU, util/GO9PTERM
Modify GO9PTERM and GO9PCPU to use hostfwd option to redirect ports.
Resolves issue #360
Signed-off-by: Michael Arnold <myk321@gmail.com>
=> Stop using depreciated -redir option when launching qemu

util/GO9PTERM
Enable Harvey terminal to start by fixing incorrect qemu command in GO9PTERM.
Commit 4219943 that was intended to fix defect defect #360, contains errors in GO9PTERM.  GO9PCPU works as expected.
Signed-off-by: Michael Arnold <myk321@gmail.com>
=> Correct GO9PTERM qemu command

sys/src/9/port/devcap.c
I forgot we actually are using devcap, and made a mistaken
push to sha256. That's going to be a while on Harvey.
=> devcap: undo a mistake

util/GO9PCPU, util/GO9PTERM
q35 = ICH9 (not FX440 with pc)
smp 1 is by default, today all the 64 bit processors
have at least two cores.
=> Qemu scripts XXI century

sys/src/9/amd64/devacpi.c, sys/src/libacpi/harvey.c
I am trying to get oriented around the acpi stuff and created a small test program that uses the acpica library according to the programmer's reference. In doing so, I found some small errors preventing the ACPICA library from working properly. The out pio functions in the custom part of libacpi had their arguments reversed. Also, devacpi had ioalloced the ACPI ports preventing userspace from accessing them.
The test program I used is as follows (built in /sys/src/cmd/acpi):
```
#include <acpi.h>
void main(int argc, char *argv[])
{
ACPI_STATUS status;
status = AcpiInitializeSubsystem();
if (ACPI_FAILURE(status))
exits("failed to init subsystem");
status = AcpiInitializeTables(NULL, 4, 0);
if (ACPI_FAILURE(status))
exits("failed to init tables");
status = AcpiLoadTables();
if …
```
=> Get ACPICA AcpiEnableSubSystem to work properly

.build, sys/src/9/amd64/BUILD, sys/src/libc/BUILD, sys/src/libthread/BUILD
=> bldy: envinroment variables can now be used in paths

util/src/harvey/cmd/elf2c/elf2c.go
This will let us get rid of the hard-coded entry point address.
=> elf2c: emit the entry point of the ELF file too

sys/src/9/boot/boot.c
screenconsole does not work on riscv yet. But riscv provides
fails.
Also add a boot.ld script so riscv toolchain doesn't set up
boot incorrectly.
=> boot: make boot able to user #P/cons if it is there

sys/src/9/riscv/devarch.c
=> riscv: take out leftover debug print for consoleread

amd64/include/klib.json
I had not kept klib.json up to date.
clang-build amd64 kernels boot again.
=> amd64: fix clang booting

sys/src/libc/BUILD
=> Adding mising syscall to bldy BUILD file in libc

sys/src/9/port/chan.c, sys/src/9/port/portfns.h
The function belongs to sysfile.c which is in port hence moved to portfns.h
=> Move prototype of checkdc into portfns.h

sys/src/regress/build.json, sys/src/regress/cow.c, sys/src/regress/empty.c
Empty does nothing, but can fail in some circumstances. cow tests copy
and write (and fails on riscv).
=> Add two more tests

sys/src/9/port/devvcon.c, sys/src/cmd/9pvpxy.c, sys/src/cmd/build.json
I previously proposed to add 9p support to the virtio-serial-pci driver (aka virtconsole) but this was not accepted. Here I am proposing a similar solution, but using an userspace proxy program. The program (9pvpxy) simply reads 9p messages from its std input and sends to the virtqueue, receiving buffers from the virtqueue and minimally massaging them to write 9p messages of proper length to its std output.
Example usage:
```
srv -e '9pvpxy /dev/virtcon/virtio-console-2' vc2
mount -c -n /srv/vc2 /mnt/xxx
```
The proxy was tested same way as the 9p virtio was tested (dd file read-write). It showed lower speeds and less stability than the 9p native virtio, but it allows to have arbitrary 9p servers on the host (ufs is just an example) while native 9p does not allow that (cannot be connected …
=> 9p proxy over virtqueue

sys/src/9/riscv/assembly.S, sys/src/9/riscv/build.json, sys/src/9/riscv/devarch.c, sys/src/9/riscv/fns.h, sys/src/9/riscv/trap.c
Due to a bug in the RISCV simulator we were able to set
mtimecmp (still allowed) and also able to clear the
Supervisor Timer Interrupt Pending (STIP) bit. That bit
can only be cleared in M-mode but SPIKE let us do it.
We had to change timerset to do an mcall.
Conflicts:
sys/src/9/riscv/devarch.c
=> riscv: use the SBI call to set mtime compare (mtimecmp)

sys/src/libstdio/dtoa.c
reported in https://scans.sevki.io/1567/report-af964f.html#EndPath
=> libstdio: fix malloc size. double -> bigint

sys/src/9/amd64/tcore.c
reported in https://scans.sevki.io/1567/report-754299.html#EndPath
=> sys/src/9/amd64: change malloc size in tcore to ACVctl from Vctl

sys/src/cmd/acme/cols.c, sys/src/cmd/acme/dat.h, sys/src/cmd/acme/ecmd.c, sys/src/cmd/acme/exec.c, sys/src/cmd/acme/look.c, sys/src/cmd/acme/rows.c, sys/src/cmd/acme/text.c, sys/src/cmd/acme/wind.c
Having to cast these string literals to (Rune*) doesn't look great, but it does remove the warnings for now, as previously mentione in #14.
=> Fix rune warnings in acme

sys/src/cmd/acpi/irq.c, sys/src/libacpi/olsneracpi.c
This fixes the last warning in the ACPI code.
=> Change IRQRouteData pin to UINT64

amd64/include/cflags.json, amd64/include/klib.json, sys/src/9/amd64/core.json
We should have a better solution, rather than one that relies on the exact location of the compiler, but this will do for now.
=> Fix mac build (on my machine at least)

amd64/x86_64-elf-gcc.BUILD, sys/src/9/amd64/BUILD, sys/src/9/amd64/clang-3.7.BUILD, sys/src/9/amd64/clang-3.8.BUILD, sys/src/9/amd64/clang-3.9.BUILD, sys/src/9/amd64/clang.BUILD, sys/src/9/amd64/gcc-4.8.BUILD, sys/src/9/amd64/gcc-5.BUILD, sys/src/9/amd64/gcc-6.BUILD, sys/src/9/amd64/gcc.BUILD
now using the amd64/$CC.BUILD flags for everything
R=rminnich
R=elbing
Signed-off-by: Sevki Hasirci <s@sevki.org>
=> bldy: remove the sys/src/9/amd64 specific compiler flags

amd64/include/cflags.json, amd64/include/clang-3.4.json, amd64/include/clang-3.5.json, amd64/include/clang-3.6.json, amd64/include/clang-3.7.json, amd64/include/clang-3.8.json, amd64/include/clang.json, amd64/include/gcc-4.8.json, amd64/include/gcc-5.json, amd64/include/gcc-6.json, amd64/include/gcc.json, amd64/include/icc.json, amd64/include/x86_64-elf-gcc.json, amd64/include/x86_64-none-elf-gcc.json
I should have done it this way in the first place.
=> cflags: remove ToolOpts and just use include

sys/src/libc/amd64/main9.S
llvm on OSX seems to default to 32-bit, which is stupid, but
easy to fix.
Tested to booting on linux.
=> libc/amd64/main9.S: force it to code64

util/src/harvey/cmd/build/build.go
Typical build no longer needs sh, so remove from tool dependencies.  Defaults to 'sh', but can be overridden with SHELL environment variable.  This gets us closer to being able to build on mac with gcc.
=> Fix remaining problems for build on mac concerning sh

sys/src/9/amd64/core.json
Final change required to get harvey building with macosx/gcc/build.
=> Apply TOOLPREFIX to objcopy

lib/namespace
Ensures /dev/rtc is available for both cpu and terminal.
=> Add binding for /dev/rtc

.travis.yml, bootstrap.sh
Bldy is a brilliant prototype but we want to rethink some aspects
of its implementation. Until we're sure how it's going to work
out, take it out of the test matrix (it's pushing our travis
times to 30 minutes) and don't get it or mention it in
bootstrap.sh. Do this in a way that lets us bring it back
when we're ready.
=> bldy: let bldy take a vacation for a bit

sys/src/9/amd64/devacpi.c
macdonag reports getting a flood of interrupts on his hardware.
I am not sure that's supposed to happen, but this IS ACPI,
so all bets are off.
=> acpi: don't enable gpes until acpiintr is opened

sys/src/9/port/portclock.c, sys/src/9/port/sysproc.c
Now that we have an official HarveyOS organization, we can have a more formal copyright policy.
The policy from here on out is as follows:
- we don't remove personal copyrights from imported code
- when we create code, the copyright is HarveyOS
- we don't add personal copyrights to code
- if needed, when substantial changes are made, we'll add a HarveyOS copyright notice.
We expect this to be infrequent.
If we find other places where we have added personal copyrights since the
Harvey project began, we will remove them as well.
This policy accords with modern practice on projects such as Harvey.
=> Remove personal copyrights

sys/src/libmp/port/cnfield.c, sys/src/libmp/port/gmfield.c, sys/src/libmp/port/mpfield.c, sys/src/libmp/port/mpnrand.c, sys/src/libmp/port/mptober.c, sys/src/libsec/port/ecc.c, sys/src/libsec/port/jacobian.c, sys/src/libsec/port/secp256r1.c, sys/src/libsec/port/secp384r1.c, sys/src/libsec/port/tsmemcmp.c
As Ron said:
Now that we have an official HarveyOS organization, we can have a more formal copyright policy.
The policy from here on out is as follows:
- we don't remove personal copyrights from imported code
- when we create code, the copyright is HarveyOS
- we don't add personal copyrights to code
- if needed, when substantial changes are made, we'll add a HarveyOS copyright notice.
We expect this to be infrequent.
If we find other places where we have added personal copyrights since the
Harvey project began, we will remove them as well.
This policy accords with modern practice on projects such as Harvey.
=> Remove more personal copyrights.

sys/src/9/386/i8042.c
When you press twice a dead key it's like if you press it three times. This solve it.
=> Solved little bug in dead key repetition

sys/src/cmd/gdbserver/gdbstub.c
=> gdbstub: correctly require that a pid be set

sys/src/cmd/gdbserver/gdbstub.c
Fixes issue #496 - handling of vMustReplyEmpty.
This is a very specific fix, can improve code in a later PR.
=> Improve handlign of unsupported commands

sys/src/cmd/acme/text.c
Fixes #500 and returns up/down arrow keys to the traditional
behavior. We can use zenith for experimentation and different
keyboard behavior.
=> Fix #500 (acme crashes on arrow key down)

sys/src/cmd/gdbserver/gdbstub.c
Status was checked incorrectly, and if we respond with Einval for qTsV, gdb will go into an infinite loop.  Return 0 for these qT* packets instead.
=> Check and respond to qT* packets correctly

sys/src/libc/libc.json
=> gdb: don't remove 9syscall source files, gdb gets confused.

sys/src/cmd/gdbserver/gdbstub.c
This is because the process may be blocked on a syscall.  Perhaps we can move this to a child process in the future, but for now, since it's blocking the gdb connection and causing a timeout, just remove it.
=> Don’t try to stop process on gdbserver connection

lib/namespace
if you don't have /apex but if you do have apex it will give
you troff and awk etc.
=> Bind /apex/$cputype/bin to /bin by default. It won't hurt you

sys/src/9/port/devproc.c
When copying a text segment into a data segment for writing, setup permissions correctly.  Similarly when duplicating data as text.  These changes needed because SG_RONLY was replaced with SG_READ and SG_WRITE, and SG_LOAD seems to have been added as a replacement for SG_TEXT, but the work wasn’t completed.  We should either work out what was intended, or remove the change in the future.
=> When writing to text segments, handle both SG_TEXT and SG_LOAD

.gitignore, sys/src/libfreetype/src/base/ftstroker.c, sys/src/libfreetype/src/bdf/bdflib.c, sys/src/libfreetype/src/cache/ftlru.c, sys/src/libfreetype/src/raster/ftraster.c, sys/src/libfreetype/src/sfnt/ttcmap0.c, sys/src/libfreetype/src/sfnt/ttload.c, sys/src/libfreetype/src/type1/t1gload.c, sys/src/libfreetype/src/type1/t1objs.c
Mostly unused variables, or set-but-unused.
The unfortunate practice seems to be to define a variable,
initialize it to zero, and set it to one later.  Then, presumably,
someone could look at it with a debugger or something and see
that it had been set at some point (or not).  Perhaps this is
used as a rough signal to see that something has happened in a
function.
Unfortunately, an optimizing compiler will probably note that
the variable is set but unused and just remove it.  So we just
remove some of them ourselves.  Or whatever.
=> Cleaned up warnings in libfreetype

sys/src/cmd/gdbserver/debug_core.c, sys/src/cmd/gdbserver/gdbstub.c
Once breakpoint has been hit, gdb fails because it can’t write back the instruction.  Still need to tidy up lots of this code, but at least it shows we can hit a breakpoint.  It's all very scrappy, but we're further down the path at least.
Some todos:
- Close files
- Modify rmem and wmem to go via map, then remove setbp call
- Handle breakpoint note on behalf of process being debugged
- Replace breakpoint instruction
- Handle removal of breakpoints
etc...
=> Can set and hit a breakpoint to a stopped process

sys/include/libc.h, sys/src/9/port/lib.h
Rewrite this macro so it doesn't cause a spurious
warning about braces.
=> Fix assert() so that it doesn't warn

sys/src/cmd/yacc.c
Fix a bug in folding C strings with escaped newlines in C
code snippets in yacc.  This bug has existed since Plan 9
second edition in 1995.
=> Fix a bug in yacc.

sys/src/cmd/gdbserver/debug_core.c, sys/src/cmd/gdbserver/gdb.h, sys/src/cmd/gdbserver/gdbstub.c
- wmem and rmem now use put1 and get1, so access process text and data via the map.
- dbg_remove_sw_break handles removal of active breakpoints.  When a breakpoint is hit, gdb will request that the breakpoint is removed via z0, and then reinserted when continue is requested, via Z0.  This change now behaves correctly (I think).
- Removed some unused code
The next step is to remove the breakpoint note to stop the process suiciding before we continue.
=> gdbserver - improvements when hitting a breakpoint

sys/src/cmd/auth/factotum/secstore.c
`==` has higher precedence than `&`. This caused half
of an expression to always be 0.
=> Fix a bug in factotum's secstore support.

sys/src/cmd/gdbserver/gdbstub.c, sys/src/libmach/access.c
When the breakpoint has been hit, we read the process note to stop it from suiciding.  This could probably be improved a bit by handling the case where there are multiple notes.
Also fix some logging formatting issues.
=> gdbserver - continue after hitting breakpoint

amd64/include/gcc-6.json, sys/src/9/amd64/main.c, sys/src/libc/port/getcallerpc.c, sys/src/libc/port/getcallstack.c
We need to replace this code with assembler, I think.
=> Use pragmas to turn off warnings about __builtin_return_address

sys/src/cmd/aux/realemu/pit.c
'+' has higher precedence than '<<'.
=> Fix BCD calculations in realemu.

sys/src/cmd/aux/realemu/xec.c
At least one of these was out-of-order with a longjmp().
Fix the indentation on many others to make them less
obscure.
=> Fix print_func_exit() calls.

sys/src/cmd/aux/vga/vmware.c
=> Fix a real bug in aux/vga/vmware.c.

sys/src/cmd/ip/httpd/httpd.c
This change also removes a warning. It's interesting
how often warnings point out code that's not idiomatic,
or can be rewritten to make it simpler and clearer.
=> Rewrite part of httpd to simplify some code.

sys/src/9/amd64/trap.c
Again, a precedence bug; this time in the kernel.
Fixed with parenthesis.
=> Fix a bug in amd64/trap.c

sys/src/9/port/elf64.c
Another operator precedence bug.
=> Fix a bug in port/elf64.c.

sys/src/9/amd64/core.json, sys/src/9/port/port.json
It's portable code but needs some non-portable support.
=> keyboard: move devkbmap to the architecture

sys/src/9/port/devproc.c, sys/src/libmach/map.c
The format of /proc/pid/segment changed in commit 121208f.  Originally, if a segment was read-only, 'R' would be shown after the segment name.  In the case of the stack, this would be absent.  After that commit, there would always be a token displaying the segment permissions, therefore changing the format.  Also, due to the optional 'P' token, it is difficult to parse reliably.
The symptom was that any mapped data segment didn't include the stack.  This was because the change in format to segment meant when creating the map, we were reading the lower address for the stack, rather than the top.  This showed up when trying to view the stack in gdbserver -
e.g. displaying backtrace.
This commit also combines the 'P' token with the permission section so we always know which tokens are where. …
=> Fix bug in libmach where mapped data segment didn't include stack

sys/src/cmd/gdbserver/gdbstub.c
Setting a variable (e.g. 'set foo=123') was broken.  This is because ebin2mem was overwriting the src rather than the dest for some reason.  wmem would then copy the dest (which hadn't been touched since the malloc...)
The first commit is the actual fix, the second tidies some things up a bit.
=> Fix gdb writing to memory

sys/src/9/port/error.h, sys/src/cmd/ip/telnet.c, sys/src/cmd/ip/telnetd.c, sys/src/cmd/tar.c, sys/src/libacpi/acpica/acpiflags.json, sys/src/libstdio/dtoa.c
Compiled with clang 4.0 on my dev machine.
=> Fix warnings exposed by clang>3.8.

sys/src/cmd/gdbserver/kdb/kdb_support.c
=> Replace a call to `__builtin_return_address(0)` with `getcallerpc()`

sys/src/regress/apexnotecont.c
This is what I see apex doing in its signal handler.
It fails badly, indicating a kernel bug.
=> regress: add a test for apex note handling problem

sys/src/cmd/gdbserver/gdb.h, sys/src/cmd/gdbserver/gdbstub.c, sys/src/cmd/gdbserver/regsaarch64.c, sys/src/cmd/gdbserver/regsamd64.c, sys/src/cmd/gdbserver/regsriscv.c, sys/src/libmach/access.c
Rather important for getting the stack pointer to step out of functions.
Also tidy the formatting of some error messages that showed up alongside the bug.
Seems the list of registers is duplicated in sys/src/9/amd64/dat.h
We should probably pick one place for this to avoid the duplication.
=> Implement get_reg for gdbserver

sys/src/libufs/port-scripts/list-spatch-breakers.sh, sys/src/libufs/port-scripts/macros.h
Gives us the following list of:
../ufs/dirhash.h
../ufs/extattr.h
../ufs/inode.h
../ufs/quota.h
../ufs/ufs_dirhash.c
../ufs/ufs_quota.c
../ffs/ffs_extern.h
../ffs/ffs_snapshot.c
../ffs/ffs_softdep.c
../ffs/ffs_vfsops.c
../ffs/softdep.h
The script can be adapted for future ports.
=> Add a script that will list all UFS files that break spatch

sys/src/libufs/ufs/freebsd_util.h, sys/src/libufs/ufs/inode.h, sys/src/libufs/ufs/quota.h, sys/src/libufs/ufs/ufs_bmap.c
Pull some defines and typedefs from FreeBSD into freebsd_util.h.
Remove some defines that wouldn't do anything in C.
Fix includes and signatures in ufs_bmap.c.
=> Trying to get ufs_bmap.c to build (part 1)

rc/bin/usbstart
=> Remove reference to #U in usbstart

sys/src/cmd/newfs/build.json
This doesn't build because of missing BSD headers, but it at least let's you try and build using util/build
=> Add build.json for newfs

sys/include/libc.h
=> libc.h: no, we won't compile on gcc 2. Deal with it.

sys/src/cmd/newfs/mkfs.c, sys/src/cmd/newfs/newfs.c
Remove code that was guarded by an #if 0 block in newfs, and references to
an undefined __FBSDID macro.
Signed-off-by: Dave MacFarlane <driusan@gmail.com>
=> Remove dead code in newfs

sys/src/cmd/newfs/build.json, sys/src/cmd/newfs/newfs.c, sys/src/cmd/newfs/newfs.h, sys/src/libufs/ufs/freebsd_util.h
- Add header from libufs which defines some FreeBSD types for Harvey rather
than duplicating the effort, and '#if 0'ed out the FreeBSD headers which
don't exist.
- Add a couple FreeBSD ufs types needed for newfs to libufs header
Signed-off-by: Dave MacFarlane <driusan@gmail.com>
=> newfs: Remove FreeBSD headers and add header from libufs

sys/src/9/ufs/ffs/ffs_vfsops.c, sys/src/9/ufs/ffs/fs.h, sys/src/9/ufs/ufs/freebsd_util.h, sys/src/9/ufs/ufs/ufsmount.h, sys/src/9/ufs/ufs_harvey.h
Malloc the ufsmount struct, but comment out all fields we don't yet use - some we won't need at all, so we'll add them back as necessary.
Remove GJOURNAL related code.  We won't be supporting this.
Typdef some structs.
=> A little more work on UFS mounting

sys/src/9/ufs/ffs/ffs_vfsops.c, sys/src/9/ufs/freebsd_util.h, sys/src/9/ufs/ufs/ufsmount.h
Bit of a milestone - we can now read from specific disk blocks, not just a byte offset.  Doing it this way, and using a wrapper function, keeps the bread interface very similar to FreeBSDs, hopefully avoiding some bugs during the port.
=> UFS: A little more mounting

sys/src/9/ufs/ffs/ffs_extern.h, sys/src/9/ufs/ffs/ffs_snapshot.c, sys/src/9/ufs/ffs/ffs_softdep.c, sys/src/9/ufs/ffs/ffs_vfsops.c, sys/src/9/ufs/ffs/softdep.h, sys/src/9/ufs/freebsd_util.h, sys/src/9/ufs/ufs.json, sys/src/9/ufs/ufs/quota.h, sys/src/9/ufs/ufs_harvey.h
This brought in a lot of scattered changes unfortunately.  I've disabled snapshots for now (NO_FFS_SNAPSHOT).  Another slight bit of ugliness is 'struct workhead'.  Need to keep the struct due to the way the LIST_HEAD macro works.  If I change that (yes, I tried) then it breaks somewhere else that calls the macro as so: LIST_HEAD(, snapdata)....
=> UFS: Mounting the (disabled) softdep data

sys/src/9/ufs/ffs/ffs_vfsops.c
These flags aren't used in UFS, and seem more relevant the FreeBSD kernel, so let's assume we can remove them for now.
=> UFS Remove unnecessary code

sys/src/9/port/devufs.c, sys/src/9/ufs/ffs/ffs_vfsops.c, sys/src/9/ufs/ufs_harvey.h
echo unmount > /dev/ufs/0/ctl
will now unmount mountpoint 0.
Also embedding the mountpoint ID in the qid path, as seen in devproc.
=> UFS Add ctl file for devufs mountpoints

sys/src/9/ufs/ffs/ffs_balloc.c, sys/src/9/ufs/ffs/ffs_extern.h, sys/src/9/ufs/ffs/ffs_subr.c, sys/src/9/ufs/ffs/ffs_vfsops.c, sys/src/9/ufs/ufs/acl.h, sys/src/9/ufs/ufs/extattr.h, sys/src/9/ufs/ufs/inode.h, sys/src/9/ufs/ufs/quota.h, sys/src/9/ufs/ufs/ufs_lookup.c, sys/src/9/ufs/ufs/ufsmount.h
...all of this is in the kernel anyway.
=> UFS Get rid of _KERNEL define

sys/src/9/port/devufs.c, sys/src/9/ufs/ffs/ffs_vfsops.c, sys/src/9/ufs/ffs/fs.h, sys/src/9/ufs/ufs/ufsmount.h, sys/src/9/ufs/ufs_harvey.c, sys/src/9/ufs/ufs_harvey.h
- Don't need code to identify mount as UFS since it's the only choice
- Add in some stats and parameters from fs that we will need later
- A couple of small bits of tidying
=> Use ID rather than mount name for UFS

sys/src/9/port/devufs.c, sys/src/9/ufs/ffs/ffs_vfsops.c, sys/src/9/ufs/ufs.json, sys/src/9/ufs/ufs_ext.h, sys/src/9/ufs/ufs_harvey.c, sys/src/9/ufs/ufs_harvey.h, sys/src/9/ufs/ufs_mountpoint.c, sys/src/9/ufs/ufs_mountpoint.h
- ffs_vgetf will get an existing vnode or pick one from freelist
- vnodes for same inode are now shared and reference counted
- freelist of vnodes maintained on mountpoint
- vnode lists on mountpoint protected by qlock
- added stats file to mountpoint
- started to tidy up code with ufs_ext.h for externally facing definitions
=> UFS Mountpoint vnode management, sharing

sys/include/ufs/freebsd_util.h, sys/include/ufs/libufs.h, sys/include/ufs/ufsdat.h, sys/src/9/ufs/ffs/ffs_balloc.c, sys/src/9/ufs/ffs/ffs_inode.c, sys/src/9/ufs/ffs/ffs_snapshot.c, sys/src/9/ufs/ffs/ffs_vfsops.c, sys/src/9/ufs/ufs/ufs_vfsops.c, sys/src/9/ufs/ufs_harvey.c, sys/src/9/ufs/ufs_harvey.h, sys/src/libufs/block.c, sys/src/libufs/cgroup.c, sys/src/libufs/libufs_subr.c, sys/src/libufs/sblock.c, sys/src/libufs/type.c
ufsdat.h currently only has the header required by both libufs/block.c and the main UFS code.  It will grow as the other libufs/*.c files compile, and with some of the ffs_subr and ffs_tables declarations.
=> Get libufs/block.c compiling without errors + 1st pass at ufsdat.h

sys/include/ufs/libufs.h, sys/src/libufs/libufs.json, sys/src/libufs/type.c
I removed ufs_disk_fillout and ufs_disk_fillout_blank from type.c altogether.  They're used in newfs, but they don't seem to be used outside the 'file' path.  If I'm wrong, we can add it back.
=> Get last bits of libufs compiling

sys/src/9/ufs/ffs/ffs_vfsops.c
=> Fix ufs crash if trying to mount file with bad fs

sys/include/ufs/dir.h, sys/src/9/ufs/ufs/ufs_dirhash.c, sys/src/9/ufs/ufs/ufs_lookup.c, sys/src/9/ufs/ufs/ufs_vnops.c, sys/src/cmd/newfs/mkfs.c
By assuming that we only handle 'new' file systems with a fs_maxsymlinklen > 0, we can avoid all the LITTLE_ENDIAN tests.
=> Remove all LITTLE_ENDIAN tests from ufs code

sys/include/ufs/dir.h, sys/src/9/ufs/ufs/ufs_dirhash.c, sys/src/9/ufs/ufs/ufs_lookup.c, sys/src/9/ufs/ufs/ufs_vnops.c
Again based on the assumption that mnt_maxsymlinklen > 0 for our filesystems, and therefore OFSFMT always returns 0.
=> Remove old-style dir templates, some code for old-style file systems

sys/include/ufs/freebsd_util.h, sys/include/ufs/inode.h, sys/src/9/port/devufs.c, sys/src/9/ufs/ffs_extern.h, sys/src/9/ufs/ffs_vnops.c, sys/src/9/ufs/ufs_harvey_external.c, sys/src/9/ufs/ufs_harvey_internal.c, sys/src/9/ufs/ufs_vnops.c, sys/src/9/ufs/ufsdat.h, sys/src/9/ufs/ufsfns.h
cat /dev/ufs/0/inodes/<fileinode>/data
Also handle file offsets better when dumping files or directories.
Quite a few todos here.
=> Enable reading of files in UFS

sys/src/libscribble/graffiti.c, sys/src/libscribble/graffiti.h, sys/src/libscribble/hre_api.c, sys/src/libscribble/hre_internal.h, sys/src/libscribble/li_recognizer.c, sys/src/libscribble/scribbleimpl.h
commit 6533db6114e97d5687bdb6a0f94136c98d009408
Date:   Mon May 1 00:00:16 2017 +0000
Remove trailing whitespace from source files.
This is a trivial cleanup (done with a script, Ron!).
commit 789474da8c5122316f7ee093a02e84a4aed24ad2
Date:   Thu Apr 20 17:59:21 2017 +0000
Kill a couple of thousand warnings.
These are the easy ones. I've got a few hundred left.
commit 9fba51d999489cf1bf2adf3a35c2260caebf0c32
Author: Ronald G. Minnich <rminnich@gmail.com>
Date:   Wed Jul 6 13:09:10 2016 -0700
fixfmt: fix all usages of %u so that u is a type, not a modifier
The rest of the world uses %u to mean unsigned decimal. Plan 9
uses …
=> Reintroduce libScribble

sys/src/libString/libString.json, sys/src/libString/s_alloc.c, sys/src/libString/s_copy.c, sys/src/libString/s_getline.c, sys/src/libString/s_grow.c, sys/src/libString/s_memappend.c, sys/src/libString/s_nappend.c, sys/src/libString/s_parse.c, sys/src/libString/s_rdinstack.c, sys/src/libString/s_read.c, sys/src/libString/s_read_line.c
commit 1d0e45488f79506550e2f841ebe415b6bd1fb92a
Author: Ronald G. Minnich <rminnich@gmail.com>
Date:   Sun Apr 24 13:01:24 2016 -0700
clang: fix libString
commit 331ffebb5394eb0768cea498e43a2d2c98829e9d
Author: Sevki Hasirci <s@sevki.org>
Date:   Mon Feb 22 00:55:22 2016 +0100
just the files
commit 48090c023db7a9d0f4f36f3b270dc30080c24ce5
Author: ron minnich <rminnich@gmail.com>
Date:   Sun Feb 14 05:49:03 2016 +0100
Revert "build: added new …
=> Reintroduce libString

sys/src/libusb/BUILD, sys/src/libusb/audio/audioctl.c, sys/src/libusb/audio/audiofs.c, sys/src/libusb/audio/audiosub.c, sys/src/libusb/build.json, sys/src/libusb/disk/disk.c, sys/src/libusb/disk/scsireq.c, sys/src/libusb/ether/asix.c, sys/src/libusb/ether/cdc.c, sys/src/libusb/ether/ether.c, sys/src/libusb/ether/smsc.c, sys/src/libusb/kb/hid.c, sys/src/libusb/kb/kb.c, sys/src/libusb/lib/dev.c, sys/src/libusb/lib/devs.c, sys/src/libusb/lib/dump.c, sys/src/libusb/lib/fs.c, sys/src/libusb/lib/fsdir.c, sys/src/libusb/lib/parse.c, sys/src/libusb/print/print.c, sys/src/libusb/serial/ftdi.c, sys/src/libusb/serial/prolific.c, sys/src/libusb/serial/serial.c, sys/src/libusb/serial/silabs.c, sys/src/libusb/serial/ucons.c
commit 313973c85082becd8a5ffe1974b3d967138958f4
Author: Ronald G. Minnich <rminnich@gmail.com>
Date:   Sun Apr 30 17:18:20 2017 -0700
JSON: run preen on json files
Long overdue:
./util/preen -d=false `find . -name "*.json" -print`
Preen needs some cleanup. I never changed it since for a while util/build
was going away. But it still works.
commit 331ffebb5394eb0768cea498e43a2d2c98829e9d
Author: Sevki Hasirci <s@sevki.org>
Date:   Mon Feb 22 …
=> Reintroduce libusb

amd64/include/u.h, sys/include/libc.h, sys/src/libc/9sys/read.c, sys/src/libc/9sys/write.c
Bringing up wirte and read from ap/lib/_write.c and ap/lib/_read.c
in APEX.
=> Importing read and write from APEX

sys/src/libthread/386.c, sys/src/libthread/BUILD, sys/src/libthread/amd64.c, sys/src/libthread/arm.c, sys/src/libthread/channel.c, sys/src/libthread/create.c, sys/src/libthread/dial.c, sys/src/libthread/exec.c, sys/src/libthread/id.c, sys/src/libthread/lib.c, sys/src/libthread/libthread.json, sys/src/libthread/note.c, sys/src/libthread/power.c, sys/src/libthread/rendez.c, sys/src/libthread/riscv.c, sys/src/libthread/sched.c, sys/src/libthread/threadimpl.h
commit 3272435e1b2cccd4cd4def9e6237f1c586662d70
Author: Dan Cross <crossd@gmail.com>
Date:   Wed Jul 27 19:47:02 2016 -0400
Skeleton aarch64 files: minimum needed to build most libraries. (#230)
Add the very minimum files needed to build most Harvey libraries:
these are just placeholders.
commit 331ffebb5394eb0768cea498e43a2d2c98829e9d
Author: Sevki Hasirci <s@sevki.org>
Date:   Mon Feb 22 00:55:22 2016 +0100
just the files
commit …
=> Reintroduce libthread

sys/src/libregexp/libregexp.json, sys/src/libregexp/regcomp.c, sys/src/libregexp/regexec.c, sys/src/libregexp/rregsub.c
commit 331ffebb5394eb0768cea498e43a2d2c98829e9d
Author: Sevki Hasirci <s@sevki.org>
Date:   Mon Feb 22 00:55:22 2016 +0100
just the files
commit 48090c023db7a9d0f4f36f3b270dc30080c24ce5
Author: ron minnich <rminnich@gmail.com>
Date:   Sun Feb 14 05:49:03 2016 +0100
Revert "build: added new build files"
Does not work at all. Can't build a working system with it yet.
Let's take this slower, ok? Not break it all next time.
This reverts commit 4fd75744926150212a0c0cd3c5a2ea51d0637d12.
Change-Id: …
=> Reintroduce libregexp

sys/src/libplumb/libplumb.json, sys/src/libplumb/mesg.c
commit 48090c023db7a9d0f4f36f3b270dc30080c24ce5
Author: ron minnich <rminnich@gmail.com>
Date:   Sun Feb 14 05:49:03 2016 +0100
Revert "build: added new build files"
Does not work at all. Can't build a working system with it yet.
Let's take this slower, ok? Not break it all next time.
This reverts commit 4fd75744926150212a0c0cd3c5a2ea51d0637d12.
Change-Id: I91fce92249dd9d7bf3ca731a124c61a499382dd2
commit 4fd75744926150212a0c0cd3c5a2ea51d0637d12
Author: Sevki <sevki@spotify.com>
Date:   Wed Jan 27 …
=> Reintroduce libplumb

sys/src/liboventi/client.c, sys/src/liboventi/liboventi.json, sys/src/liboventi/pack.c, sys/src/liboventi/packet.c, sys/src/liboventi/packet.h, sys/src/liboventi/parsescore.c, sys/src/liboventi/plan9-io.c, sys/src/liboventi/plan9-sha1.c, sys/src/liboventi/plan9-thread.c, sys/src/liboventi/rpc.c, sys/src/liboventi/scorefmt.c, sys/src/liboventi/server.c, sys/src/liboventi/session.h, sys/src/liboventi/strdup.c, sys/src/liboventi/zero.c
commit 400364d361586e548bd7c08d8cdcb64a4bc69e90
Author: Ronald G. Minnich <rminnich@gmail.com>
Date:   Wed Jul 6 13:53:16 2016 -0700
fixfmt: with this last round of changes I can boot.
commit 48090c023db7a9d0f4f36f3b270dc30080c24ce5
Author: ron minnich <rminnich@gmail.com>
Date:   Sun Feb 14 05:49:03 2016 +0100
Revert "build: added new build files"
Does not work at all. Can't build a working system with it yet.
Let's take this slower, ok? Not …
=> Reintroduce liboventi

sys/src/lib9p/srv.c
- Removed Ebadattach due to it's not used
=> Reintroducing lib9p

sys/include/libc.h, sys/src/libc/9sys/abort.c
=> Use clang/gcc compatible builtin for abort to avoid clang error

sys/include/libc.h, sys/src/9/port/portclock.c, sys/src/cmd/vnc/compat.c, sys/src/libc/9sys/abort.c, sys/src/libc/port/_assert.c, util/src/harvey/cmd/mksys/mksys.go
- assert doesn't need to be restrict to const.
- builtin_trap is an alternative for abort under certain circumstances,
our need is the original loop.
- aesthetic fix in mksys.go for boot methods
=> Various fixes:

sys/src/libthread/channel.c
Undo some changes from ac5494c22127f601346841986a1f80d18a542129
Looks like that commit was meant to fix some compiler errors.
We go back to the original code and fix the errors in a more direct way.
=> Fix for libthread - fixes vga/realemu interaction

sys/src/9/amd64/dat.h, sys/src/cmd/gdbserver/build.json, sys/src/cmd/gdbserver/gdb.h, sys/src/cmd/gdbserver/gdbstub.c, sys/src/cmd/gdbserver/regs.c, sys/src/cmd/gdbserver/regsaarch64.c, sys/src/cmd/gdbserver/regsamd64.c, sys/src/cmd/gdbserver/regsriscv.c
Describe registers in table.  Preparation for handling FPU regs.
Also fix gdbreg size in devproc and gdbserver - we seem to have chopped off the last two registers by mistake.
=> Restructure gdbserver register handling

sys/src/9/386/vgavesa.c, sys/src/9/amd64/mmu.c, sys/src/9/boot/boot.c, sys/src/libacpi/harvey.c
Those messages now under DBG are useful for implementing
ACPI or debugging and error. In Qemu there's only a line,
In real hardware around 2 hundred.
Same for mmu and vgavesa, not hundreds, but see useless messages
if it's not debugging time.
=> Cleaning some messages from boot

sys/src/regress/vseprint.c
Test formatting of doubles.  Breaks on clang 5.0.1, passes on gcc 7.3.1
=> regress/vseprint tests more formats - breaks on clang 5, passes on gcc 7.3

sys/src/9/amd64/dat.h, sys/src/9/amd64/fpu.c
Simplifies the management of the saved FPU state a little.
Fxsave needs to be aligned to 16 bytes.  Using the aligned attribute seems like a nicer way of doing it.
=> Specify alignment of Fxsave struct by using aligned attribute

sys/src/9/amd64/archamd64.c, sys/src/9/amd64/devarch.c, sys/src/9/amd64/fns.h, sys/src/9/riscv/devarch.c
There's no need for a function and dev telling about number
of cores in the cpu, it should be part of the dev/cputype.
Now cputype can handle all the supported cpus in amd64/archamd64.c
For now seems nobody tried harvey in a machine without an AMD or Intel
processor, but who knows.
With this change, every supported cpu added to archamd64 will be showed
in dev/cputype.
TODO: some specific family and model info.
=> Upgrading cputype

sys/src/9/amd64/amd64.h, sys/src/9/amd64/fpu.c, sys/src/9/amd64/l64acidt.S, sys/src/9/amd64/l64idt.S, sys/src/9/amd64/tcore.c, sys/src/9/amd64/trap.c, sys/src/9/riscv/tcore.c
Not sure why it's called #XF here - maybe that was an old name for it?  It seems to be named #XM everywhere in the Intel guide, other than 3 references to #XF, and is vector 19 (not 18 as stated in a comment).
=> Rename #XF exception to #XM to match Intel docs

util/GO9PCPU, util/GO9PCPUDOCKER, util/GO9PTERM
- net dump is deprecated.
- GO9PTERM had -smp 2 unlike rest which is 4
=> Updating GO9P* scripts to Qemu 2.10

sys/src/cmd/acme/acme.c
This patch should mitigate the bug 615 for Acme, but the error is still present in Harvey, this is only a way to recover the shell after exit from Acme
=> Mitigate bug 615

sys/src/9/amd64/sdiahci.c, util/img/prepfs
We get the retry blk message in iario because ci is cleared between the time it's set and we test it before sleeping.  We don't clear ci manually, but it can be cleared if the ST flag on p->cmd is cleared (and probably for other reasons too).  We clear the st flag at various points throughout the sdiahci code
This fix is a little hacky, but ensures we always sleep at least once, which would always happen in the usual case anyway.
This change also includes a script to build a fossil file system and do a large dircp.  This currently functions as a test, but will become a script to build the plan 9 file system for an image.
=> Avoid unnecessary retries in sdiahci

sys/src/9/amd64/usbuhci.c
not sure how this happened but ...
-               if(sts != 0xFFFF && (sts & PSreserved1) == 1){
+               if(sts != 0xFFFF && ((sts & PSreserved1) == PSreserved1)){
=> fix mistaken compare

sys/include/usb/audio.h, sys/src/libusb/audio/audioctl.c, sys/src/libusb/audio/audiosub.c
Selector_control seems to have been partially disabled a long time ago, but some code still assumed it existed.
Clang caught the code trying to access an array entry out of bounds.
=> Fix clang 7 build of usb audio

sys/src/9/amd64/vsvm.c
This was set to an absurdly high value, meaning that
random bits of the kernel were being consulted to check
permissions for unprivileged code to perform programmed
IO.  Set it to sizeof(Tss) to mark it as not used.
See the SDM for more information.
=> TSS: set IO map base address correctly.

util/src/harvey/cmd/build/build.go, util/src/harvey/cmd/build/codegen.go
This makes the build predictable and comparable - can now compare build output.
Also remove timestamps from build step logging, again for ease of comparison.
=> Iterating over go maps don't guarantee order, so sort before iterating

sys/src/9/boot/boot.c
This fixes the the first part of the long-standing USB init bug we've had.
Can now use usb keyboard by adding '-device usb-kbd' to the qemu options, but it seems hyper-sensitive - press a button and get 10 chars.  There also seems to be some warnings about a descriptor on usb init.  That's the next step.  Also usb mouse doesn't seem to work from startup.  It /seems/ to work if you add the mouse (in qemu) mid-session though.  Maybe?
=> exec(usbd) args weren't nil terminated, so broke on init

sys/man/3/kbin, sys/src/9/boot/boot.c, sys/src/9/port/devkbin.c, sys/src/cmd/usb/usbd/usbd.c, sys/src/libusb/kb/kb.c
kbin used iota for the dev identifier, this looks near-identical to I, so changed to #j.  Also fix an intended reference in boot.c to this device.
While I'm at it, fixed some print formatting in usbd.
=> Change kbin dev to #j, fix ref in boot.c, fix usb print

sys/src/cmd/acpi/irq.c, sys/src/libstdio/vfscanf.c, sys/src/regress/libc/scanf.c
Shows importance of brackets around blocks!
Lack of brackets caused scanf to fail to parse more than one value
Add test for scanf
=> Fix scanf - some va_end calls needed to be bracketed

sys/src/cmd/init.c
This is a tiny PR that adds some messages indicating when termrc and cpurc are started by the init process. This makes the order of events in the init process more clear to everyone.
=> Makes the order of events in init clearer in the log

CONTRIBUTING.md
Link in CONTRIBUTING.md searched for ‘newbie friendly’ tags
whereas issues are tagged with ‘good first issue’ instead.
Signed-off-by: Dato Simó <dato@net.com.org.es>
=> Fix list of newbie friendly issues to use the right tag.

sys/src/9/amd64/apic.h, sys/src/9/amd64/devacpi.c, sys/src/9/amd64/fns.h, sys/src/9/amd64/io.h, sys/src/9/amd64/ioapic.c, sys/src/9/amd64/main.c, sys/src/9/amd64/mpacpi.c, sys/src/9/amd64/trap.c, sys/src/9/port/devcons.c, sys/src/9/riscv/fns.h, sys/src/cmd/acpi/irq.c
If run on real hardware with multiple functions on a single PCI device, the original code falls over, since it doesn't seem to distinguish between functions of a PCI device.  This change attempts to improve that, and also to tidy up some code and debug statements
=> Tidy up APIC code, try to handle multiple function PCI devices

sys/src/9/386/386.json, sys/src/9/386/nv_dma.h, sys/src/9/386/vganvidia.c, sys/src/9/amd64/build.json, sys/src/cmd/aux/vga/nvidia.c
Re-add from https://github.com/0intro/plan9
Modified to build.  Fails when on when vga connects to nvidiammio segment.  So another reason to fix segments.
=> Re-add vganvidia - kernel support for old nvidia cards

sys/src/cmd/ip/telnet.c, sys/src/cmd/ip/telnetd.c
Just let kernel place it before stack - avoids any problems due to large page size, too much heap allocated, etc.
=> telnet* - don't specify shared segment location in segattach

sys/src/9/amd64/cbvga.c, sys/src/9/amd64/mmu.c, sys/src/9/amd64/vga.c, sys/src/cmd/aux/vga/nvidia.c
Use same explicit nv codenames in nvidia code as nouveau
Make nvidia code a little safer so we can dump out data even if it's a little incomplete
=> Ensure vga physical segs are read/write+attached with default page size

sys/src/cmd/acid/acid.h, sys/src/cmd/acid/acid.json, sys/src/cmd/acid/builtin.c, sys/src/cmd/acid/dbg.y, sys/src/cmd/acid/dot.c, sys/src/cmd/acid/exec.c, sys/src/cmd/acid/expr.c, sys/src/cmd/acid/lex.c, sys/src/cmd/acid/list.c, sys/src/cmd/acid/main.c, sys/src/cmd/acid/print.c, sys/src/cmd/acid/proc.c, sys/src/cmd/acid/util.c, sys/src/cmd/acid/y.tab.c, sys/src/cmd/acid/y.tab.h, sys/src/cmd/build.json
Removed the plan 9 extensions compile flag, fixed all errors caused by this, and add it to the build.
Can run `acid /bin/ls`.  Stops at main, can then continue.  Haven't tried more than that, but it seems like a good start :)
=> Add acid to default build, fix lots of build errors

sys/include/a.out.h, sys/include/elf.h, sys/include/mach.h, sys/src/cmd/acid/acid.h, sys/src/cmd/acid/builtin.c, sys/src/cmd/acid/main.c, sys/src/cmd/gdbserver/gdbserver.c, sys/src/cmd/ktrace.c, sys/src/cmd/strip.c, sys/src/libmach/executable.c, sys/src/libmach/obj.c, sys/src/libmach/setmach.c, sys/src/libmach/sym.c
Some debugger/libmach changes:
- Add elf symbol support to libmach
- Fix up acid as far as being able to run and set breakpoints.  Can now load elf symbols, set breakpoints, etc.  Not used extensively though.  No support for dwarf data in programs, so no line numbers, etc.
- Add ability for gdbserver to launch programs and immediately break in _main (hang).  Make debugging **much** easier
- Add support for gdbserver continuing to completion without error (previously assumed it would hit a breakpoint)
=> launch program support for gdbserver, elf symbol support for acid

sys/src/cmd/gdbserver/gdbserver.c
otherwise when we try to get the segments of the program we're debugging, we could get those of the forked process *before* the exec.  Which really isn't what we want.
=> gdbserver wait for launched program to stop before attaching

usr/harvey/lib/profile
If anyone has a better way of doing it (since I'm crap at rc) go ahead
(This was breaking a bunch of go tests, btw(
=> Fix bug where tmp wasn't bound properly since syscall doesn't exist

sys/src/9/amd64/entry.S, sys/src/9/amd64/main.c
Add assert if end of elf is past that limit.
Fixes crash after building with clang 9.
=> Increase initial kernel identity map size to 16MiB

sys/src/9/amd64/fpu.c, sys/src/9/amd64/l64fpu.S
- Solves -nan issue with printf
- regress/fpu/_fpustate now always works (not random)
Tested on *REAL* machine and with GCC (not Clang)
=> Initializing properly the FPU

sys/src/sysconf.json, util/src/harvey/cmd/mksys/mksys.go
This change allows us to easily offset Harvey system call numbers from some base. The base is now in sysconf.json as SyscallBase.
This will in turn let us, if we wish, also support traditional Plan 9 system calls.
=> Allow us to easily renumber harvey system call numbers

sys/src/9/amd64/syscall.c, sys/src/sysconf.json, util/src/harvey/cmd/mksys/mksys.go
This reverts commit 839f2c9424bd390b6fac34dfb12ad79c5521d6bc.
It also removes the addition of 1024 to the plan 9 scall number.
Turns out we don't need it; up->plan9 is good enough.
=> Revert "Renumber harvey system call numbers"

sys/src/9/amd64/devacpi.c
This broke on hardware.
Also, tell Ron not to put delays like that in code.
It's a bad practice.
And also keep it to a separate line to make git blame
easier.
=> remove delay(1000) in devacpi.c

sys/src/9/amd64/syscall.c, sys/src/sysconf.json, util/src/harvey/cmd/mksys/mksys.go
This reverts commit 01481e298a86de9e872a9459bcce96d1cd1e7604.
I have no idea why this broke it but ... it did.
This gets go working again for tip of tree.
=> Revert "Revert "Renumber harvey system call numbers""

amd64/gcc.json, sys/src/9/amd64/gcc.json
gcc 10 defaults to `-fno-common`, which results in a lot of "multiple
definition" errors when linking. As suggested by the gcc documentation,
we workaround the issue for now by setting the `-fcommon` flag:
https://gcc.gnu.org/gcc-10/porting_to.html#common
=> Fix build for gcc version 10

sys/src/9/386/i8042.c, sys/src/9/amd64/devacpi.c, sys/src/9/amd64/entry.S, sys/src/9/amd64/main.c, sys/src/9/amd64/multiboot.c, sys/src/9/amd64/vsvm.c
When I ported this to att assembly, and brought in coreboot code,
I unknowingly broke multiboot args. This fixes them.
The code is nasty, but assembly always is.
If at any point you are tempted to change this, you MUST test with
a multiboot boot and a normal boot.
=> Fix multiboot args

bootstrap.sh
Go otherwise complains:
go get: cannot install cross-compiled binaries when GOBIN is set
=> bootstrap.sh: remove GOBIN for cross-compiled binary

sys/src/9/amd64/archamd64.c, sys/src/9/amd64/asm.c, sys/src/9/amd64/mmu.c, sys/src/9/amd64/multiboot.c
Add the signature.
Fix allocator issues. coreboot reports page 0 as reserved and this breaks
the address space map allocator. Coreboot also reports memory starting at
0xc0000 as usable, and the asm code would toss that -- in the process, tossing
all of memory.
asm has turned out to be a bit fragile. It can't function without having memory
start at 0. But the code is a bit subtle, so be careful if you decide to adjust it.
Add a comment to mmuinit to explain an error message that is seen all too often.
=> Add support for PC Engines APU2 by fixing asm, multiboot

sys/src/9/386/uarti8250.c, sys/src/9/port/devuart.c
now that UARTs are showing up in #t again, any attempt to use them, e.g.
echo hi >> '#t/eia0'
will get a panic, as our interrupt support code no longer supports
ancient hardware with a tbdf of -1.
Note that, cleverly, uart interrupts are never even enabled until the
device is opened, which is why we did not see this problem earlier
We made this change I believe in the mod 2000s as part of the Fast-OS effort,
as we tried to drag the code forward from its 1990 base. It's a shame we
did not have code control back then.
i8250enable now checks to see if ctlr->tbdf is -1, or ctlr->poll is set;
if so, it disables interrupt enable.
The i8250poll code now runs, finally.
But what broke between 2011 and how such that serial consoles stopped working.
Therein lies a puzzle.
Signed-off-by: Ronald G …
=> uarti8250: make COM1 and COM2 poll, or any uart with poll or tbdf==-1

sys/src/9/amd64/main.c
It turns out that harvey now correctly handles argc, argv from
multiboot.
This means we can once again start using jmk's dbflg infrastructure.
This is important as Go programs don't currently work on smp -- WIP!
If you boot a kernel with the following cmdline:
harvey -n1
smp will be disabled and Go programs run just fine.
N.B.: argc works just like programs; switches and the rest being at argv[1]!
So put in that noise word.
Here is the kexec command I used for harvey to disable SMP:
kexec -l harvey -c 'harvey -n1' -e
Note that harvey is the first argument, not -n1.
You can, similarly, put this in syslinux.cfg or other files.
We should find other uses of dbgflg and reenable them. Further, the DBG
macro is designed to work with dbgflg, though the nasty awk script that
set all this up is …
=> Re-enable the SMP control flag

sys/src/9/port/devramfs.c
devramfs violated a lot of rules about writing drivers, in its not quite
right user (or lack of) of error etc.
It also panicked the kernel.
This verion will let your write up to a 16MiB file.
Needs work, but it's far more workable than what we had.
=> devramfs: get it to work

sys/src/9/amd64/main.c
now -v1 will get your verbose, else not.
Adding printallsyscalls=1 will get all system calls printed.
=> re-enable the vflag command line parameter; add printallsyscalls

sys/src/9/port/proc.c
An STD is when the Direction flag is inherited by the kernel from user space
and copies run backwards. A symptom is you see the kernel sending R messages
instead of T messages, when the kernel is not serving any 9p sessions.
when we reverted to the NIX scheduler in 42eba8ecadf61a25fb88710d8aae0f5f24017b14
we lost STD detection. We still have protection, but it pays to check, since
the consequences are dire.
Bring it back.
=> Restore std detection

sys/src/9/amd64/l64v.S
It was never turned on because I never understood the syntax.
This does NOT solve the Go problem on SMP.
=> implement invlpg

sys/src/9/amd64/archamd64.c
No longer hangs when trying to work out the clock multiplier
=> Make intel 0x506e0 boot

sys/src/9/amd64/sdiahci.c
Seems to have difficulty with one of the ports, causing it to hang.  Not sure why at this point, but if you skip it, it boots.
=> Add support for Intel Z170 chipset to sdiahci.c

sys/src/9/amd64/ether82563.c
Add initial support for Intel I219 ethernet.
This allows the controller to identify the I219 and makes it usable.
Takes a couple of minutes to startup, but is able to communicate across a network, and can be used to boot up with a remote ufs.
=> Add initial support for Intel I219 ethernet.

bootstrap.sh
This ensures that we have u-root and tmpfs for inclusion in
kernels.
=> Add u-root and tmpfs to the bootstrap

sys/src/9/boot/boot.c
=> Avoid running boot process twice if eia0 not found

sys/src/9/amd64/entry.S, sys/src/9/amd64/main.c
This will allow us to include a big u-root and that u-root can
contain u-root and ALL harvey binaries, i.e. all of amd64/bin.
We're going to want a better compression than just gzip.
-rw-r--r-- 1 rminnich rminnich 70192397 Aug 31 20:43 /tmp/initramfs.plan9_amd64.cpio.gz
-rw-r--r-- 1 rminnich rminnich 23180974 Aug 31 20:25 /tmp/initramfs.plan9_amd64.cpio.lzma
But we are, definitely, going to be able to have pretty much anything we need ... in the initramfs.
This is going to be pretty slick. Boot harvey, get the full graphical environment, THEN mount the
server from 9p. This would include rio etc. This is gonna be very nice.
Graham, tmpfs needs lzma added.
=> Extend initial map to 64M

sys/src/9/amd64/entry.S
We can now boot with really big ramfs.
=> Fix a stupid error that broke large images

sys/src/9/amd64/archamd64.c
We can probably move other more modern platforms up as well. At least
this one is booting much quicker now.
=> Make Haswell boot fast

sys/src/9/amd64/devacpi.c
I have no clue why it was as it was, but it looked odd.
=> Fix verbosity flag

bootstrap.sh, sys/src/9/amd64/build.json
u-root expects the sources are there in $GOPATH, so download it before
running it.
Remove an unnecessary tmpfs build since it's already being built during
bootstrap.
=> Fix build when u-root and tmpfs sources are absent from $GOPATH

sys/src/9/amd64/build.json, sys/src/9/amd64/core.json, sys/src/9/port/port.json
Somebody can fix them later but they were breaking
for an apu2 user.
=> remove coreboot and devcoreboot from the build

bootstrap.sh, go.mod, go.sum, util/ci.sh
avoids having to update commit id in bootstrap continually at cost of modifiying go.sum and go.mod
=> bootstrap: get main/master for harvey/go and u-root dependencies

sys/src/9/amd64/build.json, sys/src/9/amd64/u-root.json
It would have been nice had we been able to include all of plan 9 bin in
the initramfs. There is a problem.
For historical reasons, the amd64 KZERO is at 0xffffffff_f0000000, i.e.,
the top 256M of the 64-bit space. The u-root cpio that includes all
of /amd64/bin, when uncompressed, is 240M!
We have no space left in that top 256M, and that won't do.
It would be best, in future, if we can get KZERO to 0xffffffff_800000000,
thus making the top of the 64-bit space 2G, not 256M. I've tried this
several times and failed; there are a lot of interlocking parts that
don't make it easy.
So, for now, only put Go programs in u-root.cpio.
The new centre program makes supporting network root so easy that we
hardly need this anyway.
note that with only the go programs, u-root is not 240M, but quite …
=> shrink u-root back to go programs

sys/src/9/port/devmnt.c, sys/src/9/port/devmntn.c, sys/src/9/port/portfns.h
.L is the internet standard, like it or not.
devmntn will talk .L
This gets us here:
rminnich@rminnich-MacBookPro:~/go/src/github.com/hugelgupf/p9/cmd/p9ufs$ ./p9ufs -v -root /tmp :8080
2020/09/08 21:12:33 recv [r 0xc00000e038] [Tag 065535] Tversion{MSize: 131096, Version: 9P2000}
2020/09/08 21:12:33 send [w 0xc00000e038] [Tag 065535] Rversion{MSize: 0, Version: unknown}
2020/09/08 21:12:33 recv [r 0xc00000e038] [Tag 065535] Tversion{MSize: 131096, Version: 9P2000.L}
2020/09/08 21:12:33 send [w 0xc00000e038] [Tag 065535] Rversion{MSize: 131096, Version: 9P2000.L}
2020/09/08 21:12:33 unknown error: buffer contained no valid message
2020/09/08 21:12:33 send [w 0xc00000e038] [Tag 065535] Rlerror{Error: 5}
and here
192.168.0.8# srv tcp!192.168.0.1!8080 x
post...
192.168.0.8# mount -M N /srv/x …
=> devmntn: start conversion to 9P2000.L

sys/src/9/port/sysfile.c, sys/src/sysconf.json
When dc is 0, we try to do a bind, but since the `name` argument is nil,
we crash with `invalid address`. The fix falls back to 'M' in this case,
which also helps plan9 programs that doesn't know about dc.
Fixes #998
=> Fix crash in mount syscall when dc is 0

sys/include/fcall.h, sys/src/9/port/devmnt.c, sys/src/9/port/devmntn.c, sys/src/libc/9sys/convM2D.c, sys/src/libc/9sys/convM2S.c, sys/src/libc/9sys/convS2M.c
Working read of 9P2000.L directories. Note that you can cat
but not ls -l yet, as we don't have stat, and the first thing
ls does is stat the directory.
This works with a 9P2000.L server running at 192.168.0.1!8080
srv tcp!192.168.0.1!8080 x
mount -M N /srv/x /n/x
cat /n/x
=> readdir for 9p2000.L

sys/include/fcall.h, sys/src/9/port/devmntn.c, sys/src/libc/9sys/convM2D.c, sys/src/libc/9sys/convM2S.c, sys/src/libc/9sys/convS2M.c
Sample session with a 9P2000.L server (e.g. ipfs):
srv tcp!192.168.0.1!8080 x
mount -M N /srv/x /n/x
ls -l /n/x
9P2000.L has two big problems: first, a directory read does not return
stat records, as it should; second, the stat has fields missing, particularly
the file name, a string for uid, and a string for gid.
These are hard to work around. The result in output like this:
% ls -l/n/x
------w-r--  0 '' '' 0 Feb  7  2006 /n/x/util
because a readdir does not return stat records, we are missing user, group, size information.
But:
192.168.0.7# ls -ld /n/x
d-rwxrwxr-x N 31 1000 1000 4096 Feb  7  2006 /n/x
Because in this case, the code does a stat on /n/x and gets a stat record back.
Now for the first case, what has to happen, but not in this PR, is on a readdir,
the code must do a full …
=> stat for 9P2000.L / devmntn

sys/src/9/port/devmntn.c
9P2000.L servers don't seem to understand OEXEC.
devmntn mntopencreate will now convert OEXEC to OREAD.
Exec over 9P2000.L mounts work now.
=> Fix exec on 9P2000.L (devmntn)

sys/src/9/port/devramfs.c
The hostowner for ramfs is always eve, not "harvey"
We can change this if we ever need to.
We can allow rename:
192.168.0.7# touch '#@/x'
192.168.0.7# mv '#@/x' '#@/y'
192.168.0.7# ls '#@'
'#@/y'
192.168.0.7# ls -l '#@'
--rw-rw-rw- @ 0 harvey harvey 0 Feb  7  2006 '#@/y'
192.168.0.7# echo -n ron > /dev/hostowner
192.168.0.7# ls -l '#@'
--rw-rw-rw- @ 0 ron ron 0 Feb  7  2006 '#@/y'
192.168.0.7#
=> Fix file renaming and hostowner in ramfs

sys/src/9/port/devramfs.c
This corrects running programs from devramfs.
=> fix devramfs read to read all bytes requested

.gitignore, bootstrap.sh, clean.json, lib/namespace, sys/src/9/amd64/build.json, util/GO9PCPU, util/GO9PTERM
Need to decide what to keep in the util folder - I made changes to the GO9P* scripts I think we should keep.
=> Add plan9_$ARCH folder, use centre instead of ufs

sys/src/9/port/sysproc.c
Given a script of the form:
i.e. a file name that is an a.out not an ELF and, further, is not /bin/rc.
It will fail with the odd error:
execac: elf64ldseg returned 0 segs!
This is hardly intuitive. Here's the problem:
The header that is read is a script header.
It is parsed to a name and args, the name being the target file (in this case an a.out).
Namec is called with the path from the #! file (e.g. /path/to/plan9/binary)
The new file is opened and a chan returned to execac.
Aoutldseg is called to check the line. But it is the line for the old file. The line is still the #! header.
Aaoutldseg says "this !# is not an a.out" and returns -1
The elf parser is called, and it says "not an elf", as it is using the new file.
Why does it work for ELF? b/c ELF does not use the header that was read …
=> Fix problem when scripts invoke plan 9 binaries

sys/src/9/386/uarti8250.c, sys/src/9/386/uartpci.c, sys/src/9/amd64/build.json, sys/src/9/amd64/fns.h
Uart port offset found in linux.
Initialise devuart first to allow early connection to pci uart.
Can initialise by adding the following after the uart has been created in uartpci.c:
i8250uartconsole(uart, nil);
(Would be better to drive it off the kernel args or some other cfg, but no good ideas yet)
=> uartpci: add support for WCH CH382 uart pci card

sys/src/9/amd64/asm.c
If an asmalloc is large and hence consumes the first element in the list,
asmlist must be bumped to point to the next element. The code, as written,
would end up destroying asmlist and there would be no available memory
on boot. This code worked fine for well over 10 years until we found
an AMD platform with a Reserved region at the 4M mark, i.e.:
Memory
0x0000000000001000 0x00000000000a0000 (651264)
Memory
0x0000000000100000 0x0000000004000000 (66060288)
reserved
0x0000000004000000 0x0000000004042000 (270336)
Memory
0x0000000004042000 0x0000000076d00000 (1925963776)
That reserved hole broke asm completely.
=> Fix asmalloc if the first element in the list has to be removed

sys/src/9/amd64/ahci.h, sys/src/9/amd64/sdiahci.c
sdiahci was hanging when trying to intialise on a Skylake i7-6700K,
when calling ahciidle for port 5.  This appears to have been caused
by writing to 0x90 in the PCI register.  Commenting it out removes
the hang (though I haven't tested beyond that).
There seems to be a bit of init code being called for almost all
Intel controllers - this probably wasn't the original intention.
Given that the PCI registers would change from controller to
controller, this is probably not the best way to do it.  Given
that the code is quite old and therefore the controllers also,
it might be best to remove controller specific init code, follow
the AHCI spec, and see how far we can get.
I restructured the code to put more of the initialisation code in
one place.  This makes it a bit easier to see the same …
=> ahci: update ahci identification and init, remove support for esb

amd64/clang.json, sys/src/9/amd64/clang.json
clang11 requires -fcommon flag to put tentative definitions into the common section
=> clang11 requires -fcommon flag for harvey

sys/src/9/amd64/ahci.h, sys/src/9/amd64/sdiahci.c
also remove flags that aren't really flags - they're > 1 bit
=> ahci: add support for cap2 flags

sys/src/games/mp3enc/lame.c
There is a small typo in sys/src/games/mp3enc/lame.c.
Should read `specified` rather than `specifed`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, specifed -> specified

sys/src/9/port/devcons.c
putstrn is called by print. When multiple cpus call it
we get output like this:
54cupc3up 2uc 1oc locolorol ro- r1-  1-r 1or lorelo elT eCT  CTt Cst cst cs3 c93 993899789078107910491449544
5
s
2 lhcsehcdehidenidinitin:ti :tn :onb o s ocsnhco htof c ofosrorc rehc  :pc fupao3ulr
c
This is hard to read.
With this simple lock we get this:
unknown color for cpu1
ioapicintrinit: success
virtio-9p initializing
unknown color for cpu2
schedinit: no sch for cpu3
CPU Freq. 1400MHz
unknown color for cpu3
schedinit...
virtio-serial-pci initializing
acpiintr: gpe 1 on
read fault fail, no segment, pid 1 addr 0x89c04320e pc 0xffff80000030dc28
acpiintr: calling gpe 1
panic: cpu1: fault: 0x89c04320e
die:wait forever
This is easier to read, altough it is hard to understand :-)
Signed-off-by: Ronald G. …
=> Put a lock around putstrn so output is readable

sys/src/9/amd64/dat.h, sys/src/9/amd64/l64v.S, sys/src/9/amd64/syscall.c
Get rid of `STACKPAD` in syscall.c.
=> Clean up setlabel/gotolabel

sys/src/regress/kernel/eatmem.c
On a T510 running with the new VM, it fails instantly with
a fault on 0xffff8001f8000000.
=> Add a regression test for consuming memory

sys/src/9/amd64/mmu.c
As we map each page of the address space, the amount
of address space we need to map decreases by the page
size we just mapped.
=> Fix mapping error

sys/src/9/port/devregress.c
The walk entry lets us see how things are mapped, e.g.
192.168.0.7# echo -n 0xffff800000000000>'#R/walk'
cpu0: pml4 0xffff8000034c5000
cpu0: mmu l3 pte 0xffff8000034c5800 = 111023
cpu0: mmu l2 pte 0xffff800000111000 = 1602023
cpu0: mmu l1 pte 0xffff800001602000 = 1606023
cpu0: mmu l0 pte 0xffff800001606000 = 8000000000000003
192.168.0.7#
This whould help us debug some current problems, and also
understand how things end up being mapped.
=> Add a walk entry to devregress to test VM mappings

bootstrap.sh, go.sum, rc/bin/cpurc, sys/src/9/amd64/allbuild.json, sys/src/9/amd64/gocmds.json, sys/src/9/amd64/gocmdswithmods.json, sys/src/9/amd64/u-root.json, sys/src/9/port/devroot.c
If you build `sys/src/9/amd64/allbuild.json`, then run cpu, cpurc will extract the uroot archive to the ramdisk and bind it to root.
=> Alternative kernel build.json (allbuild.json) that adds uroot archive to ramdisk and extracts in cpurc

amd64/include/ureg.h, sys/src/9/amd64/l64idt.S, sys/src/9/amd64/l64vsyscall.S, sys/src/9/amd64/trap.c
Commit 6ab2e16c9f1058aab427f79d4516d281c8e6039b removed these
segmentation registers, but we still need them for Go programs to work
correctly.
The Go runtime uses ureg.sp when it needs to print a stack trace after
the program dereferences a nil pointer and receives a note from the
kernel. Since sp comes after the segmentation registers in the struct,
the sp offset within the struct would be wrong if the segmentation
registers are missing.
After this change, Go programs will now panic (and print a stack trace)
instead of crashing when dereferencing a nil pointer.
Fixes #999
=> Add back [DEFG]S registers to Ureg

sys/src/9/amd64/kernel.ld
=> Don't discard debug sections when linking the kernel

sys/src/9/amd64/multiboot.c
This kernel is too silent when it needs to be informative.
=> If there are no multiboot tables, have the courtesy of telling us

rc/bin/urootrc, sys/src/9/amd64/allbuild.json, sys/src/9/boot/boot.c, sys/src/9/port/error.h, sys/src/cmd/init.c, usr/harvey/lib/profile, util/GO9PUROOT
The uroot service is a clone of terminal.  This can be the starting point to remove and tidy what we don't want.
If sys/src/9/amd64/allbuild.json is built (adding the uroot archive to the kernel ramdisk) it will unpack that to devramfs, bind it to root and bind /bbin to /bin, before other binaries.
To test:
- build everything
- build sys/src/9/amd64/allbuild.json
- run util/GO9PUROOT
=> Add uroot service as a clone of terminal

.github/workflows/harvey.yml, util/build-img.sh, util/img/syslinux-bios/syslinux/syslinux-usb.cfg
Guestfish uses the extlinux command installed on the system and the
version of syslinux install on the system may be different from the one
that comes with Harvey. If we mix syslinux versions, boot can fail. For
example, I was getting this when booting from an image created on an
ArchLinux system:
```
Undef symbol FAIL: x86_init_fpu
Failed to load libcom32.c32
Failed to load COM32 file vesamenu.c32
```
Help #1072
=> util/build-img.sh: use system syslinux binaries

rc/bin/urootrc, sys/src/9/amd64/allbuild.json, util/GO9PUROOT
Load uroot cpio as initrd, and try to unify the build a bit more.  We no longer need allbuild.json, there are just 3 extra files in the kernel ramdisk (decompress, cpio and urootrc).
To build and run with uroot:
- bootstrap
- build
- build sys/src/u-root.json
- run util/GO9PUROOT
=> uroot.cpio.lzma is now the initrd rather than embedded in the kernel ramdisk

CONTRIBUTING.md, util/prepare-commit-msg
This will automatically sign off commits. See also:
https://stackoverflow.com/questions/15015894/git-add-signed-off-by-line-using-format-signoff-not-working/46536244#46536244
=> Add prepare-commit-msg script

.gitignore, clean.json, sys/src/u-root.json
To use, add `--- uroot.cpio.lzma` to the pxelinux file as described [here](https://github.com/Harvey-OS/harvey/wiki/Booting-Harvey-on-real-hardware-I-(TFTP)#preparing-the-host).
Note that at least on my machine, I get a page fault.  Fixing that would be the next step.  (Maybe it doesn't happen on other machines?)
=> Copy uroot to tftp folder when built

sys/src/9/amd64/memory.c
If module memory sections exist (e.g. when using initrd), and there's a usable memory larger than 2Mi between the end of the kernel memory and the start of the module, harvey would try to use it as user memory, despite it being found to be earlier than sys->pmstart (as set in setphysmembounds).  This would cause a page fault when physinit was later called for that memory section.
This commit will avoid using any PamMEMORY sections found earlier than any PamMODULE sections.  This has the downside that we lose useful memory, but probably not very much.  In my case the memory section was just under 6Mi.
Maybe this can be recovered with a more sophisticated change (probably involving physalloc.c)?
This change should have no effect if modules (initrd) are not used.
Signed-off-by: Graham …
=> Avoid page fault due to partially initialised memory sections

sys/src/9/amd64/archamd64.c, sys/src/9/amd64/dat.h, sys/src/9/amd64/usbuhci.c, sys/src/9/riscv/archriscv.c, sys/src/9/riscv/dat.h
It was named uintmem because uint is 32-bits and we needed a
physical address type that was kind of uint but really for physical
addresses and hence 64 bits, while, at the same time, not being
tied to a bit length (so u64 would not do).
This all goes back to the days of the 32-bit transition for K10 IIRC.
This is all very confusing so give it a name related to its function.
=> rename uintmem to physaddr

sys/src/cmd/frontusb/disk/disk.c, sys/src/cmd/frontusb/joy/joy.c, sys/src/cmd/frontusb/kb/kb.c, sys/src/cmd/frontusb/lib/dev.c, sys/src/cmd/frontusb/lib/usb.h, sys/src/cmd/frontusb/serial/ch340.c, sys/src/cmd/frontusb/serial/ftdi.c, sys/src/cmd/frontusb/serial/prolific.c, sys/src/cmd/frontusb/serial/serial.c, sys/src/cmd/frontusb/serial/silabs.c, sys/src/cmd/frontusb/usbd/hub.c, sys/src/cmd/frontusb/usbd/usbd.c
run ref.cocci to update incref/decref uses
```spatch --sp-file sys/src/spatches/ref.cocci sys/src/cmd/frontusb/**/*.c --in-place```
=> frontusb: ref spatch changes (incref, decref)

sys/src/cmd/frontusb/lib/dump.c, sys/src/spatches/getcallerpc.cocci
spatch --sp-file sys/src/spatches/getcallerpc.cocci sys/src/cmd/frontusb/**/*.c --in-place
=> frontusb: fix getcallerpc + spatch

sys/src/9/ip/devip.c, sys/src/9/port/dev.c, sys/src/9/port/dev9p.c, sys/src/9/port/devenv.c, sys/src/9/port/devether.c, sys/src/9/port/devmnt.c, sys/src/9/port/devmntn.c, sys/src/9/port/devmouse.c, sys/src/9/port/devramfs.c, sys/src/9/port/devsegment.c, sys/src/9/port/devsrv.c, sys/src/9/port/portdat.h, sys/src/9/port/portfns.h
Device create functions changed to return Chan* created, similar to open.
Required for integration of devshr.
Looks to have been added because shrcreate has a path where a new Chan is created, in which case it wants to sent the new chan rather than the one passed in.
As mentioned in slack, the 9front commit this change is based on is: https://code.9front.org/hg/plan9front/rev/2e0310025a75
```
changeset:   771:2e0310025a75
user:        cinap_lenrek@centraldogma
date:        Wed Aug 17 23:27:31 2011 +0200
summary:     change definition of Chan.create to return a chan like open
```
=> Dev create signature changed to return Chan*

sys/include/9p.h, sys/src/lib9p/post.c, sys/src/lib9p/rfork.c, sys/src/lib9p/thread.c
These are used by the 9front usb stack, but were missed in the previous devshr PRs.
=> devshr: add postsharesrv and threadpostsharesrv functions

sys/include/9p.h, sys/src/lib9p/lib9p.json, sys/src/lib9p/queue.c
9pqueue will be used by the 9front usb/serial code.
From the man page:
Reqqueue provides routines for deferred processing of 9p request in multithreaded 9p servers.
There are 2 commits - the first is the unadulterated 9front code, the second contains the changes to get it building in harvey.
=> Import 9pqueue from 9front

util/GO9PCPU, util/GO9PCPUDOCKER, util/GO9PIMG, util/GO9PIMGUSB, util/GO9PTERM, util/GO9PUROOT
If kvm is enabled, the GO9P* scripts use the older 'pc' machine config, rather than the newer q35 config.
This means we don't have an ahci device amongst other things.
Switching to q35 to have a more modern config (and ahci).
A couple of consequences of the change:
- The default qemu config has a dvd drive.  This seems to cause a couple of i/o errors to show up in harvey.
- We can now attach images as drives by adding the following lines to the qemu line in GO9P*:
```
-drive id=disk,file=harveyhd.img,if=none \
-device ahci,id=ahci \
-device ide-,drive=disk,bus=ahci.0 \
```
These will now be picked up by devsd.
=> GO9P* scripts should use qemu q35 machine when using kvm

sys/src/cmd/ip/ipconfig/main.c
Despite what the man pages say, ip/ipconfig can actually take 300 seconds to time out on acquiring a DHCP lease. That's because it runs up to 30 iterations of a function which itself retries DHCP requests 10 times, once per second. This will instead give up after 20 seconds, which should be more than enough and is much more in-line with what the man page claims.
=> Make ip/ipconfig give up quicker on DHCP

sys/src/cmd/git/log.c
Changes formatting of long dates in git log.  Shouldn't make a difference.  Sufficient to get git to build and run.
=> git: change time-related log code to use our libc rather than 9front (fix git build)

build/build.bash
if GOLANG_HARVEY is set, the script does a bin mount to sys/go
from there, go will be included.
Tested and "just works".
The amount of memory for qemu had to be bumped to 4096m.
Depending on what is in $GOLANG_HARVEY, the CD may or may not be
big enough.
=> Add support for bringing in Go

build/mkdirs, dist/replica/plan9.proto
Git was being compiled, but its script library was not included in the
distribution.
Add /sys/lib/git to mkdirs
Add /sys/lib/git to dist/replica/plan9.proto
[really just pipecleaning my git process here...]
Signed-off-by: Paul Lalonde <plalonde@acm.org>
=> Fix git9 build in the distribution.

lib/namespace
The system boots and this seems fine whether that
directory exists or not.
=> Bind /sys/go/bin/plan9_$cputype into /bin

.gitignore, 386/bbin/build.bash, build/build.bash, build/mkdirs, lib/namespace
u-root builds its busybox'ed binaries into one binary,
rewriting all commands into packages and compiling
them all at once. This process takes about 30s, end to end.
The construction is performed by the u-root command itself.
The commands need not be all u-root commands, e.g.
GO111MODULE=off GOOS=plan9 GOOS=386 u-root plan9 github.com/nsf/godit
will add the godit editor, for 386, using the plan9
template for u-root (which only adds commands
known to work on Plan 9).
In fact, u-root is happy to build images with zero u-root commands.
It's not picky.
On Plan 9, for each command, u-root creates a #! file, e.g.
for date:
This will run /bbin/bb with one argument, #!date.
The form of the second argument is carefully chosen
not to break the various shells and kernels in use.
This style of #! is …
=> Add support for using u-root

build/build.bash, build/scripts/funcs, build/scripts/usb
instead of using mkusbboot.
I'd appreciate if a few people tested this. Running build.bash should now generate both the ISO and the USB image.
=> Introduce a slightly modified version of the 9legacy usb build script

sys/src/cmd/go/commands, sys/src/cmd/go/fetchrepos.rc, sys/src/cmd/go/fetchrepos.sh, sys/src/cmd/go/mkfile
The format of the command file changes slightly.
The first field is the directory to cd into to build the command.
The rest are the git URL and directory name as before.
Some URLs comtain many commants.
Only commands with a URL are used in the fetch.
Lines like this:
name ...
are not used in a fetch, only a build.
To simplify the build step, use build -o /$objtype/bin/
instead of go install, so even names of the form a/b/c
will work easily.
=> Allow for more Go commands

sys/src/9/pc/l.s, sys/src/9/pc/trap.c
Add labels in rdmsr to indicate which path to take on a failure.
Add GPF handler.
In GPF handler, switch on ureg->pc value, and if an address is handled,
fix uref->pc.
This is basically what is done in linux, minus all the fancy ELF and
linker set machinations. It will work just fine.
=> WIP: change rdmsr to be safe

sys/src/9/pc/l.s, sys/src/9/pc/trap.c
0. Names.
1. Plan 9 formatting in the switch in trap.c
2. Add declarations for `mayberdmsr` and `rdmsrfail`
3. Assembly language tweaks
=> rdmsr: minor tweaks.

sys/src/9/pc/fns.h, sys/src/9/pc/io.h, sys/src/9/pc/l.s, sys/src/9/pc/trap.c, sys/src/9k/k10/l64v.s, sys/src/9k/k10/trap.c
Our assembler doesn't understand number labels
and the 'f' and 'b' syntax.  Case labels in a
switch must refer to compile-time constants.
=> Fixed rdmsr.

sys/src/9/pc/etherif.h
This isn't the max number of ethernet cards supported
on a particular system, but how many can be linked into
the kernel.
The new 82563 driver expanded this number significantly.
=> etherif.h: Extend MaxEther to 64.

sys/src/9/port/page.c
=> remove mistaken include from 9 kernel

sys/src/9/port/devtls.c
tlsbwrite() would call checkstate() before calling tlsrecwrite()
to make sure the channel is open. however, because checkstate()
only raises the error, the Block* passed wont be freed and
would result in a memory leak.
move the checkstate() call inside tlsrecwrite() to reuse the
error handling that frees the block on error.
[Authored by Cinap for 9front; DCO ok for Harvey by cross@:
9front uses the MIT license for all changes unless otherwise
noted: http://fqa.9front.org/fqa0.html#0.2.4.4]
=> devtls: fix bwrite memory leak when channel stops being open

sys/src/cmd/6l/BUILD, sys/src/cmd/6l/unixcompat.c
This is the first in a series of scripts that will let us build the toolchain on linux.
Adapted from NxM, but better: it's just two files for 6l, and it's buildable right in the tree.
=> Allow building 6l on unix

sys/src/cmd/6a/BUILD, sys/src/cmd/6c/BUILD, sys/src/cmd/6c/math.h, sys/src/cmd/6l/unixcompat.c, sys/src/cmd/8a/BUILD, sys/src/cmd/8c/BUILD, sys/src/cmd/8c/math.h, sys/src/cmd/8l/BUILD
8c && 6c are statically linked. I did not test 8c with .so
but 6c segv's if not statically linked.
=> build 6c and 6a, 8c, 8a, 8l

sys/src/cmd/4l/l.h, sys/src/cmd/5l/l.h, sys/src/cmd/6l/l.h, sys/src/cmd/8l/l.h, sys/src/cmd/9l/l.h, sys/src/cmd/il/l.h, sys/src/cmd/kl/l.h, sys/src/cmd/ql/l.h, sys/src/cmd/vl/l.h
This fixes a problem seen when building clock.c with 8l.  Sometimes the literal would be 32 chars - not leaving enough space for the null.  So let's just increase to 64 and be consistent across all linkers
=> Double size of literal string in linkers

build/BUILD_IN_DOCKER, build/Dockerfile, sys/src/BUILD, sys/src/BUILDTOOLCHAIN, sys/src/RUN_BUILD_IN_PRIVATE_NAMESPACE, sys/src/cmd/6a/BUILD, sys/src/cmd/6c/BUILD, sys/src/cmd/6l/BUILD, sys/src/cmd/8a/BUILD, sys/src/cmd/8c/BUILD, sys/src/cmd/8l/BUILD, sys/src/cmd/BUILD, sys/src/cmd/aux/BUILD, sys/src/cmd/cpp/BUILD
Build from a local folder if it's been mounted by docker
For CI, run `docker run --rm -it --cap-add SYS_ADMIN --privileged harvey:Dockerfile`
To build from the repo: `docker build -t harvey:Dockerfile . && docker run --rm -it --cap-add SYS_ADMIN --privileged harvey:Dockerfile`
To build from a local directory: `docker build -t harvey:Dockerfile . && docker run --rm -it --mount type=bind,source=$HARVEY,target=/usr/local/harvey_local,readonly --cap-add SYS_ADMIN --privileged harvey:Dockerfile`
It's not very sophisticated - it mounts the local repo, then copies it to another directory before building.  There's probably some cleverer way to do it, but it works.
It does simplify some things - the linux toolchain is placed in /usr/local/harvey_local - referred to throughout as `HARVEY_LOCAL`. …
=> Set up Dockerfile to optionally build from local folder

sys/man/8/nboot, sys/src/mkfile, sys/src/nboot/mkfile
Next is getting it on the 9fat.
=> nboot: add nboot and its efi booters to the build process

build/scripts/usb, sys/src/9/boot/boot.h, sys/src/9/boot/bootmkfile, sys/src/9/boot/bootrc.c, sys/src/9/boot/usb.c, sys/src/9/pc/pcf
You can now pick "rc" when asked "root is from". This gives you an rc
shell to set stuff up.
This change also invokes disk/fdisk and disk/prep when booting from
a USB disk. Previously, we had received partition offsets from 9load
and passed them in via the sdB0part environment variable. Since nload
doesn't do that, and we'd like to move to nload, we needed a different
way. Note that we had to add a few additional programs to /boot (namely
rc, fdisk, and prep) to make this work, but the kernel is still small.
=> Add rc to boot options, and get rid of 9load usb boot dependency.

rc/bin/termrc
The 1280x1024x32 is a wonderful aspirational setting
that fails a lot.
Use a default value: 1024x768x32 that is more likely to work.
=> termrc: set a default resolution 1024x768x32 not 1280x1024x32

sys/src/nboot/pc/sub.c
If a user chooses consoles in the range 0 to 3, nboot calls the
bios to set uart paramaters, usually badly.
Change nboot so that if the user selects 'A'..'D', it is like
setting '0'..'3' but no uart bios calls are done.
=> nboot: don't change uart settings for choice 'A'..'D'

sys/include/libc.h, sys/src/9/bcm/dat.h, sys/src/9/kw/dat.h, sys/src/9/loongson/dat.h, sys/src/9/loongson64/dat.h, sys/src/9/mtx/dat.h, sys/src/9/omap/dat.h, sys/src/9/pc/dat.h, sys/src/9/pcboot/dat.h, sys/src/9/port/syscallfmt.c, sys/src/9/port/sysfile.c, sys/src/9/port/systab.h, sys/src/9/ppc/dat.h, sys/src/9/rb/dat.h, sys/src/9/teg2/dat.h, sys/src/9/vt4/dat.h, sys/src/9/vt5/dat.h, sys/src/9k/k10/dat.h, sys/src/9k/port/syscallfmt.c, sys/src/9k/port/sysfile.c, sys/src/cmd/5i/syscall.c, sys/src/cmd/ki/syscall.c, sys/src/cmd/nmount.c, sys/src/cmd/qi/syscall.c, sys/src/cmd/vi/syscall.c, sys/src/libc/9syscall/sys.h
nmount allows use of different 9p clients in the kernel.
=> Add nmount system call
